### ISSUE TITLE
[Bug] Writing bug on Android devices makes the package almost unusable

### ISSUE THREAD

**Issue by badayumut** [AppFlowy-IO/appflowy-editor#1006]
### Bug Description

As seen in the video, writing in items such as todo list and numbered list etc creates copies and duplicates the text when we move the cursor to another line. The bug is present in the example application. There is no problem on iOS devices but only on Android devices. And this problem has existed for a long time. This bug makes the package almost unusable on Android devices.

https://github.com/user-attachments/assets/f25f8ffb-d5d1-4c06-8ff9-ecc49836dbe1

### How to Reproduce

- build and run example app on an Android device
- write something in todo list, numbered list etc,
- move cursor to another line 
- write something. and it duplicates previous line

### Expected Behavior

should work normally without text duplications

### Operating System

Android 13, 14 - Multiple Devices

### AppFlowy Editor Version(s)

4.0.0

**Comment by LucasXu0** [comment]
@badayumut Please try upgrading to the latest main branch. This issue should be resolved.
