### ISSUE TITLE
[Bug] Bold and then line break, then crash. 

### ISSUE THREAD

**Issue by springlo** [AppFlowy-IO/appflowy-editor#1008]
### Bug Description

Please see the screen recording

### How to Reproduce

![test](https://github.com/user-attachments/assets/02491196-079b-49d2-94b2-2f57505b00e5)

### Expected Behavior

Please see the screen recording

### Operating System

Mobile/iOS

### AppFlowy Editor Version(s)

Master

**Comment by LucasXu0** [comment]
@springlo I noticed that you customized the toolbar items. You can check whether you set the `selectionExtraInfo` when formatting the text as bold or a heading. If so, make sure to clear the extra info after using it.

**Comment by springlo** [comment]
thx
