### ISSUE TITLE
[Bug] Image upload button, error placeholder and hover tool bar is not visible in the dart mode

### ISSUE THREAD

**Issue by hyj1204** [AppFlowy-IO/appflowy-editor#110]
### Bug Description

I moved the following issue here since it is UIs inside Editor.
https://github.com/AppFlowy-IO/AppFlowy/issues/2293#issue-1674714268

The follow UIs need some improvements.
1. Upload text color on the button
![image](https://user-images.githubusercontent.com/14248245/236487602-f3f29b0c-5a4d-4bdc-984f-af51b97c1565.png)

2. The border(or maybe background) color in the placeholder area
![image](https://user-images.githubusercontent.com/14248245/236488052-071399e8-6d9f-44c7-8121-956117896021.png)

3. The highlight color on the toolbar
![image](https://user-images.githubusercontent.com/14248245/236488393-18099b46-4318-4e25-b9d5-6a926136edb1.png)

### How to Reproduce

Use the slash menu
Select image

### Expected Behavior

Please use all the colors from current ThemeData only(`Theme.of(context).***`), not from the EditorStyle(We are refactoring it now)

Here is some information that may be useful. Please let me know if any of the colors look unsuitable after implementation.

1. Upload text color on the button: `onSurface` or default text color
2. The border(or maybe background) color in the placeholder area: `tertiary` or default border-color
3. The highlight color on the toolbar: `primary` or default highlight color

### Operating System

MacOS

### AppFlowy Editor Version(s)

main branch

**Comment by hyj1204** [comment]
@akarsh-jain-790 
No worries. Take your time. Let me know if you have more questions.

**Comment by nurmukhametdaniyar** [comment]
@akarsh-jain-790 @hyj1204 Oh, I am sorry for that, I haven't seen that the image placeholder problem is moved here from AppFlowy itself and created a PR https://github.com/AppFlowy-IO/appflowy-editor/pull/119 for that 🥲. The issue is not closed on AppFlowy, so thought that it is free

**Comment by akarsh-jain-790** [comment]
> @akarsh-jain-790 @hyj1204 Oh, I am sorry for that, I haven't seen that the image placeholder problem is moved here from AppFlowy itself and created a PR #119 for that 🥲. The issue is not closed on AppFlowy, so thought that it is free

No problem, @nurmukhametdaniyar! And @hyj1204 I've created a [PR](https://github.com/AppFlowy-IO/appflowy-editor/pull/121) for the other parts of the issue now.
