### ISSUE TITLE
`_AppFlowyInputState` is missing implementation `TextInputClient.insertContent`

### ISSUE THREAD

**Issue by dvdmgl** [AppFlowy-IO/appflowy-editor#116]
### Bug Description

```shell
appflowy_editor-0.1.10/lib/src/service/input_service.dart:60:7: Error: The non-abstract class '_AppFlowyInputState' is missing implementations for these members:
 - TextInputClient.insertContent
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _AppFlowyInputState extends State<AppFlowyInput>
      ^^^^^^^^^^^^^^^^^^^
/opt/flutter/packages/flutter/lib/src/services/text_input.dart:1117:8: Context: 'TextInputClient.insertContent' is defined here.
  void insertContent(KeyboardInsertedContent content) {}
       ^^^^^^^^^^^^^
```

### How to Reproduce

Just migrated to flutter 3.10, changed my sdk to >=3.0, updated packages and `flutter run`.

### Expected Behavior

To run as before

### Operating System

Ubuntu 22.04.2 LTS 5.19.0-41-generic

### AppFlowy Editor Version(s)

0.1.12

### Additional Context

Flutter PR that added `insertContent` https://github.com/flutter/flutter/pull/110052

**Comment by LucasXu0** [comment]
Hey, @dvdmgl. Thank you for reporting the issue. I will migrate to version 3.10 after releasing the new version that supports mobile platforms.

**Comment by biancashouse** [comment]
ETA ?

**Comment by LucasXu0** [comment]
We will migrate to version 3.10 after the release of AppFlowy v0.2.

**Comment by 0xdesdenova** [comment]
Hello, my dudes. Awesome tool! I love it. Here is a quick fix for the time being:

Add this to src/service/input_service.dart at line 238:

```
  @override
  void insertContent(KeyboardInsertedContent content) {
    // TODO: implement insertContent
  }
```

**Comment by LucasXu0** [comment]
Hey. The new version 1.0.0-dev.1 that support flutter 3.10.x has been released.
