### ISSUE TITLE
[Bug] Chinese input composing can't backspace and enter

### ISSUE THREAD

**Issue by tilemoon** [AppFlowy-IO/appflowy-editor#120]
### Bug Description

![v3 7 12](https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/14fb86cd-f633-4682-a400-b4d25902ca54)

as gif show, the composing not changed when i press backspace.
print logs:
<img width="465" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/1b13a588-9ae3-4007-a1d4-a7cf13eee2ac">

### How to Reproduce

1. run the example app
2. enter any chinese characters(or other IME characters)
3. press `backspace` or `enter`, the composing not change.

### Expected Behavior

When i downgrade flutter version to v3.3.10, it works fine.
![v3 3 10](https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/715326b3-f00d-421d-9ae2-961d85506ca5)

composing logs:
![23addb5e-5d7b-4504-959a-ff4c2736f23f](https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/1894cb3c-58c8-4bc4-913a-1a1db1a52fea)

### Operating System

MacOS 13.3

### AppFlowy Editor Version(s)

latest(0.1.11)

**Comment by LucasXu0** [comment]
Fixed in the latest version.

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/cbb11903-6b41-485e-924e-12566f8a154b
