### ISSUE TITLE
[Migration]  Migrate Html To Node Converter to latest changes

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#139]
### Bug Description

converting html to node the documents are not rendered by the components

### How to Reproduce

Use Test Raw html
 ```
 final editorState =
              EditorState(document: HTMLToNodesConverter(rawHTML).toDocument());
```
               
<img width="972" alt="Screenshot 2023-05-29 at 11 13 11 AM" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/64377a14-d20f-45fa-aa9c-010c283607a8">

### Expected Behavior

Document Should be rendered

### Operating System

macos

### AppFlowy Editor Version(s)

latest main

**Comment by alihassan143** [comment]
@LucasXu0

**Comment by LucasXu0** [comment]
@alihassan143 please check this PR. https://github.com/AppFlowy-IO/appflowy-editor/pull/146

**Comment by alihassan143** [comment]
@LucasXu0  i checked i make some changes my own that i will make pr i hope that will help

**Comment by alihassan143** [comment]
<img width="1202" alt="Screenshot 2023-05-31 at 2 36 14 PM" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/09afd83f-2b97-4556-ad44-a9d8a1b47e29">
 @LucasXu0 
 consideration
 nested attributes in list as well as heading

**Comment by alihassan143** [comment]
@LucasXu0  you can close as completed this issue i create new issue related document to html conversion
 i am working on it when its complete i will create new pr
