### ISSUE TITLE
[Bug] Node cannot be deleted on the mobile phone

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#147]
### Bug Description

Node cannot be deleted on the mobile phone

### How to Reproduce

Continuously using the keyboard delete key on the demo results in the inability to continue deleting nodes

### Expected Behavior

Mobile sustainable deletion

### Operating System

mobile

### AppFlowy Editor Version(s)

master

**Comment by LucasXu0** [comment]
@q200892907 Thanks for reporting. Fixed it in 1.0.0-dev.1
