### ISSUE TITLE
[Bug] the configuration for the mobile platform is missing in the `pubspec.yaml` file

### ISSUE THREAD

**Issue by kw214** [AppFlowy-IO/appflowy-editor#148]
### Bug Description

The new version already supports the mobile platform, but the configuration for the mobile platform is missing in the `pubspec.yaml` file

### How to Reproduce

https://github.com/AppFlowy-IO/appflowy-editor/blob/ae8548c98ffa6516cb375e5f9c5c8a3b151ff9fa/pubspec.yaml#L6-L10

### Expected Behavior

The new version already supports the mobile platform, but the configuration for the mobile platform is missing in the `pubspec.yaml` file

### Operating System

mobile

### AppFlowy Editor Version(s)

1.0.0-dev.0

### Screenshots

![企业微信20230531-153956](https://github.com/AppFlowy-IO/appflowy-editor/assets/19725091/303d8804-ec61-4098-90ac-fe6585fd657d)

**Comment by LucasXu0** [comment]
Thank you for the reminder. I will update it soon.
