### ISSUE TITLE
[Bug] Placeholder issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#149]
### Bug Description

1. When the first node is a special node, such as HEADER, there may be a situation where placeholderText does not disappear

2. Cannot set placeholderText when the document is empty

### How to Reproduce

1. When the first node is a special node, such as HEADER, and placeholderText is displayed, directly wrapping will appear

2. Cannot set placeholderText when the document is empty

### Expected Behavior

1. When the first node is a special node, such as HEADER, when placeholderText is displayed, the line breaks directly and placeholderText disappears

2. When the document is empty, placeholderText can be set

### Operating System

all

### AppFlowy Editor Version(s)

master

### Screenshots

1、
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/a8e96712-60c8-4025-bf59-17b4452fc64b)
2、
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/41ee1084-0aa8-49f3-9a83-e50dd0fb700c)

**Comment by LucasXu0** [comment]
Hey, @q200892907. I suppose you were intending to set the placeholder text for normal text?

**Comment by LucasXu0** [comment]
<img width="323" alt="Screenshot 2023-05-31 at 20 15 56" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/74190f19-c62a-4415-b62b-05ec3a1aa54d">

If so, you can set up the block configuration like this.

```dart
      ParagraphBlockKeys.type: TextBlockComponentBuilder(
        configuration: configuration.copyWith(
          placeholderText: (_) => 'Please input something ...',
        ),
      ),
```

**Comment by q200892907** [comment]
Hi, @LucasXu0 ,if you need to implement the logic I mentioned, you need to customize the creation method field for the corresponding node. I have tried to use customization to achieve the effect. Thank you
