### ISSUE TITLE
[Bug]  Editor still editable even editable boolean is false when select on editor area

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#160]
### Bug Description

when editable is false editor still editable

### How to Reproduce

```
AppFlowyEditor.standard(
                editorStyle: const EditorStyle.mobile(),
                editorState:
                    EditorState(document: htmlToDocument(data.content)),
                autoFocus: false,
                editable: false,
              ),
```

### Expected Behavior

Editor should not be editable when editable is false

### Operating System

Android,Ios,Macos,Windows,Linux

### AppFlowy Editor Version(s)

1.0.0-dev.1

**Comment by nigeltiany** [comment]
There is also an editable property on the EditorState. Don't know if that's the fix

**Comment by LucasXu0** [comment]
I have fixed it and will release it in next version.
