### ISSUE TITLE
Document.empty is deprecated but still used

### ISSUE THREAD

**Issue by nigeltiany** [AppFlowy-IO/appflowy-editor#164]
https://github.com/AppFlowy-IO/appflowy-editor/blob/25ac5b22269965d822da4e3cf98680968baf0d73/lib/src/plugins/quill_delta/delta_document_encoder.dart#L22

Found this code still using the deprecated Document.empty

And with the root now being the page key, does the editor support paged documents?

**Comment by LucasXu0** [comment]
Thanks for reminder. What do you mean paged document?

**Comment by nigeltiany** [comment]
@LucasXu0 Imagine a situation where I need to convert the document to a pdf. This can be done blindly, hoping that nothing gets split between two pages like an image. But with a paged document, the writing canvas can represent a size document using set pixels. The pixel values that represent the size of the writting canvas can also emulate standard sizes like A4, A5 etc. This would also mean writting space could run out for a particular sized canvas hence the need for multiple pages
