### ISSUE TITLE
[Bug] htmlToDocument does not support div tag

### ISSUE THREAD

**Issue by a-v-ebrahimi** [AppFlowy-IO/appflowy-editor#174]
### Bug Description

I try to parse this, but the resulted document is empty:

```
content = "<div>Hello</div>";
final html = htmlToDocument(content);
```

But this will not return empty:
```
content = "<p>Hello</p>";
final html = htmlToDocument(content);
```

### How to Reproduce

```
content = "<div>Hello</div>";
final html = htmlToDocument(content);
```

### Expected Behavior

The html document should not be empty

### Operating System

Windows

### AppFlowy Editor Version(s)

^1.0.0

**Comment by alihassan143** [comment]
@a-v-ebrahimi  div tag now supported
