### ISSUE TITLE
[Bug] Slash Command not showing custom selectionMenuItems

### ISSUE THREAD

**Issue by Omicrxn** [AppFlowy-IO/appflowy-editor#180]
### Bug Description

I was testing out the new 1.0.0 version of AppFlowy editor and noticed that my `selectionMenuItems` on the `AppFlowyEditor.custom()` were not shown when performing the "slashCommand". As far as I could debug the variable `selectionMenuItems` is passed to the editorState but then not used anymore. Also the `standardCharacterShortcutEvents` only trigger the `slashCommand` `CharacterShortcutEvent` from `slash_command.dart` which only uses the `standardSelectionMenuItems`. However, I'm not as familiar with the AppFlowy source code as I was before v1.0 so maybe it is possible that I'm using it wrong or something since there is no documentation for this new version yet.
Thank you all for your great job in this editor I really enjoy working with it in my app.

### How to Reproduce

1. Create an `AppFlowyEditor.custom()` with the `selectionMenuItems` constructor parameter filled with some custom selection menu items.
2. On the editor press `slash` key on the keyboard to open the selection menu.
3. Notice that there are only the standard ones.

### Expected Behavior

The custom selection menu items should appear.

### Operating System

MacOS, Windows 11

### AppFlowy Editor Version(s)

1.0.0

### Screenshots

<img width="348" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/46872250/743ea1e3-1ecb-46da-a361-1b7c5c16289f">

**Comment by LucasXu0** [comment]
Hey, @Omicrxn. The documentation is outdated. Here's an example to add a selection item.

```dart
  List<CharacterShortcutEvent> get characterShortcutEvents => [
        // customize the slash menu command
        customSlashCommand(
          slashMenuItems,
          style: styleCustomizer.selectionMenuStyleBuilder(),
        ),

        ...standardCharacterShortcutEvents
          ..removeWhere(
            (element) => element == slashCommand,
          ), // remove the default slash command.
      ];

  late final showSlashMenu = customSlashCommand(
    slashMenuItems,
    shouldInsertSlash: false,
    style: styleCustomizer.selectionMenuStyleBuilder(),
  ).handler;

final editor = AppFlowyEditor.custom(
      // ...
      // customize the shortcuts
      characterShortcutEvents: characterShortcutEvents,
    );
```

**Comment by LucasXu0** [comment]
Since the selection menu is not part of the core editor, it is triggered by the slash command. Therefore, I moved this logic into the slash command event.

**Comment by Omicrxn** [comment]
Thank you for your quick answer. I like how the new API gives more flexibility, which the previous versions lacked, so separating things like the selection menu from the core editor makes a lot of sense. However, shouldn't the `AppFlowyEditor.custom()` have the `selectionMenuItems` parameter removed then? It gives a bit of confusion, if I create an editor and I see the selectionMenuItems field in the constructor my first thought would be to put my additions there like in the previous versions.

**Comment by LucasXu0** [comment]
Sure. I will remove it.
