### ISSUE TITLE
[FR] add ability to use the ":" keyword to add emojis

### ISSUE THREAD

**Issue by liyaowhen** [AppFlowy-IO/appflowy-editor#193]
### Description

In notion and google docs I'm easily able to add emojis by using the ":" keyword. For example, :smile. I just realized that GitHub can do this too. 😄 😱 . This feature will also be able to search for emojis once you type the : keyword.

### Impact

Makes it way easier to pick emojis instead of using the /emoji and clicking through the options.

**Comment by LucasXu0** [comment]
The editor supports extending it, but I believe that should be a feature of AppFlowy, which should not be included inside the editor.
