### ISSUE TITLE
[Bug] Unable to turn highlighted text to no highlight, and colored text to default text easily.

### ISSUE THREAD

**Issue by liyaowhen** [AppFlowy-IO/appflowy-editor#202]
### Bug Description

When you highlight or color text, there is no easy way to revert your changes without using Ctrl-Z or using the custom color option.

### How to Reproduce

Highlight or color text with a different color. You will see that it is hard to change the text back to its original non-formatted state without using Ctrl-Z.

### Expected Behavior

There should be an option to restore the default text (non-highlighted text or regular black text)

### Operating System

Windows 11

### AppFlowy Editor Version(s)

0.2.2

### Screenshots

![AppFlowy_4y24d7qeXV](https://github.com/AppFlowy-IO/appflowy-editor/assets/72400519/9049c4ba-94b8-42ed-af0f-c4818cd0daf3)

### Additional Context

i'm going to fix it myself

**Comment by annieappflowy** [comment]
I've seen a reset to default option in the past...
@LucasXu0

**Comment by the-jasoney** [comment]
> I've seen a reset to default option in the past... @LucasXu0

It seems to have been deleted in commit 8488c86
