### ISSUE TITLE
[Bug] Custom link with custom attribute

### ISSUE THREAD

**Issue by MichalNemec** [AppFlowy-IO/appflowy-editor#212]
### Bug Description

I need completely custom behavior for "link"
this is what im inserting:
`{"insert":"builders","attributes":{"definition":"{name: Foobar, id: 2}","bold":true}}`

based on what i found:
https://github.com/AppFlowy-IO/appflowy-editor/blob/4f077aeb2acff774e1625d123f72dc2a8c0af772/lib/src/render/rich_text/flowy_rich_text.dart#L258

it seems like i cant color my custom attributes (definition is real name), so its hard to see that its actually behaving as "link" and i dont need url launcher, i can handle that as new page navigation on my end.

### How to Reproduce

modify link which just inserts `"definition":"{name: Foobar, id: 2}"` within the text.

### Expected Behavior

able to color it myself and have control over what does it do.

### Operating System

MacOS, but its anything

### AppFlowy Editor Version(s)

1.0.3

### Additional Context

I need just an article, then special toolbar functionality, when its clicked, you can search any text definition on backend and then it inserts it. On page to read this article i can color the link and go to that definition. Whenever im creating the article itself and want to add it, i dont know if its already added, because i cant see any color, and dont want to use href, because normal links should work too. Another good example what im trying to do is to select some text custom toolbar button which enables tooltip, you write text on it, then whenever you are done, it has icon next to it, hover -> show text.

**Comment by LucasXu0** [comment]
@MichalNemec We have implemented it in this [PR](https://github.com/AppFlowy-IO/appflowy-editor/pull/244). You can customize the attributes now.
