### ISSUE TITLE
[Bug] focusNode did not work

### ISSUE THREAD

**Issue by voisbe** [AppFlowy-IO/appflowy-editor#224]
### Bug Description

There are two problems with focus.
1. The blue flicker does not disappear when unfocusing.
    - My app consists of a separate TextField for the title in the Column and an AppFlowyEditor for writing the body.
    - If I move the cursor to the TextField while writing with AppFlowyEditor, the focusing indicator (blinking blue) blinks in both places. At this time, when typing, it is normally written in the TextField.
3. focusNode doesn't work.
    - I try to use the area wide by wrapping it with expanded, but AppFlowyEditor must tap the first line to focus.
    - So I used GestureDetector and focusNode, but the focus doesn't move when I use focusNode.requestFocus().

### How to Reproduce

Scaffold(
appBar: AppBar(elevation: 0),
body: Padding(
padding: const EdgeInsets.all(18.0),
child: Column(
crossAxisAlignment: CrossAxisAlignment.start,
children: [
const TextField(),
Expanded(
child: GestureDetector(
onTap: () {
focusNode.requestFocus();
},
child: Container(
decoration:
BoxDecoration(border: Border.all(color: Colors.blue)),
child: AppFlowyEditor.standard(
focusNode: focusNode,
editorState: EditorState.blank(),
)))

### Expected Behavior

1. The blue flicker does not disappear when unfocusing.
    - Cursors should be in one place.
2. focusNode doesn't work.
    - focusNode.requestFocus() should work correctly.

### Operating System

MacOS

### AppFlowy Editor Version(s)

1.0.4

### Screenshots

![Simulator Screenshot - iPhone 14 - 2023-06-21 at 13 24 10](https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/12230133-4746-4170-8655-20330293c223)

### Additional Context

Let me know if I'm using something wrong.

**Comment by LucasXu0** [comment]
Hi, @voisbe. Normally, the cursor will be disabled when tapping on other text fields. Let me run your sample code and check it.

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/60a77ecf-1837-45fc-a968-95c1b27a82ef

Is that what you want?

**Comment by voisbe** [comment]
Yes, that's right.

**Comment by LucasXu0** [comment]
Nice. I will post the sample code after adding a new test.

**Comment by LucasXu0** [comment]
Here's the sample. https://github.com/AppFlowy-IO/appflowy-editor/pull/227/files#diff-76ec7e42110df413da4697c18277a36ef9828338b576c2062d8f8a6391023125

**Comment by voisbe** [comment]
@LucasXu0 Wow, this is the first time I've seen such quick processing. thank you very much.

**Comment by Omicrxn** [comment]
Hi! @LucasXu0  I have the same issue with exactly the same use case on both desktop and mobile. I have debugged a bit and if the `TextField` is outside the editor everything works well, however, if the text field is in the `header` field of the`AppFlowyEditor` then the issue persists.

**Comment by MichalNemec** [comment]
@LucasXu0 Hello, i have this exact issue on desktop
<img width="74" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/5663019/f40d220c-941b-48aa-a307-15320897b60a">
