### ISSUE TITLE
[Bug] currently the mobile selection is little tricky 

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#228]
### Bug Description

currently the mobile selection is little tricky 
**For Example**
when long press selection did not start the selection
handler should also be dragable 

### How to Reproduce

start select the text without double tap

### Expected Behavior

when long press on text selection start dragging where user finger drags

### Operating System

android,ios

### AppFlowy Editor Version(s)

latest

**Comment by LucasXu0** [comment]
Do you mean long-pressing the left or right handler?

**Comment by alihassan143** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/b2c4870e-57ad-499d-8155-0899d4117f2a

handler should work like this

**Comment by alihassan143** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/119a9afe-7ac9-41c1-99f8-90700ea40ad6

ios example handler

**Comment by LucasXu0** [comment]
Got it. I suppose adding a long press gesture detector will solve this problem.

**Comment by alihassan143** [comment]
yes 
also the handler also be be selectable to user can drag through handler also like android and ios handler

**Comment by LucasXu0** [comment]
Close as completed. In the latest version, we have supported the dragging gesture on Android.
