### ISSUE TITLE
[Bug]  Selection ignoring the image node

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#229]
### Bug Description

when image is added the selection ignore the image node 

### How to Reproduce

added any image node and apply select all

### Expected Behavior

image node should also be selected

### Operating System

android,ios,macos,windows,linux

### AppFlowy Editor Version(s)

latest version

**Comment by LucasXu0** [comment]
<img width="867" alt="Screenshot 2023-07-12 at 16 26 08" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/e436c038-0d0c-4901-a0d0-4d42dea6a611">

Fixed in the latest version.
