### ISSUE TITLE
[Bug] Korean language support issue

### ISSUE THREAD

**Issue by voisbe** [AppFlowy-IO/appflowy-editor#231]
### Bug Description

When I change the keyboard to Korean language and type, I get an error.

Unhandled Exception: FormatException

#0      _extension#8.shift (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:311:7)
#1      _extension#8.<< (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:308:42)
#2      _extension#2.format (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:252:26)
#3      _extension#1.format (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:238:50)
#4      DeltaTextInputService.apply.<anonymous closure> (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:68:49)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#9      new List.of (dart:core-patch/array_patch.dart:47:28)
#10     ListIterable.toList (dart:_internal/iterable.dart:214:7)
#11     DeltaTextInputService.apply (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:68:59)
#12     DeltaTextInputService.updateEditingValueWithDeltas (package:appflowy_editor/src/editor/editor_component/service/ime/delta_input_service.dart:121:5)
#13     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1857:63)
#14     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1746:20)
#15     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
#16     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
#17     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:567:35)
#18     _invoke2 (dart:ui/hooks.dart:202:13)
#19     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#20     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#21     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#22     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:723:22)
#23     _dispatchPlatformMessage (dart:ui/hooks.dart:114:31)

### How to Reproduce

Change your keyboard to Korean language and type.
"안녕하세요."

### Expected Behavior

Korean input should come out properly.
ex) 안녕하세요.

### Operating System

MacOS, iOS

### AppFlowy Editor Version(s)

1.0.4

### Screenshots
1. Typing Korean language in the appflowy official desktop app works fine.
<img width="912" alt="스크린샷 2023-06-21 오후 8 00 06" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/c0b9014b-67a9-4bb4-82c9-26c10e791d69">

2. The mentioned error occurs in the app I am implementing or in the provided sample app. An error occurs and the characters come out garbled.
<img width="349" alt="스크린샷 2023-06-21 오후 8 22 29" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/ef8ddc94-562a-432e-a18e-c6953a19b30e">

<img width="349" alt="스크린샷 2023-06-21 오후 8 22 57" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/0a31dd2a-4147-4132-8d71-33befa48f6b7">

**Comment by LucasXu0** [comment]
@voisbe Does it work as expected on the macOS?

**Comment by voisbe** [comment]
@LucasXu0 Yes, both the official and sample apps for MacOS desktop work well.
<img width="863" alt="스크린샷 2023-06-22 오후 2 34 24" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/3cd6576e-6595-4815-a6f4-dbfa13e00b52">

**Comment by LucasXu0** [comment]
@voisbe Is it what you want? I'm not sure because I don't understand the Korean input method.

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/3ee2d772-2bf0-4b2a-9d49-b941e74be4bc

Or could you help to check this PR? https://github.com/AppFlowy-IO/appflowy-editor/pull/253

**Comment by voisbe** [comment]
@LucasXu0 The issue is not resolved. Entering text with autocomplete works well, but the problem arises when typing manually character by character. I'm not very familiar with it, but I'll take a closer look at the code.

**Comment by voisbe** [comment]
@LucasXu0 No FormatException errors occur. However, there remains a problem with the characteristics of Hangul. Up to 3 characters are combined in Hangeul. Up to 2 characters are combined, but 3 characters are not created.
ex) 안녕 (o) 아ㄴ녀ㅇ (x)

- appflowy editor 
![Simulator Screenshot - iPhone 14 - 2023-06-26 at 13 17 40](https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/d0991a4b-ad29-47a2-a9f7-ae9a96724695)

- TextField
https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/ff6b40fe-91c5-4bec-b1e4-a0d8f6860829

**Comment by LucasXu0** [comment]
@voisbe Got it.

**Comment by LucasXu0** [comment]
@voisbe https://github.com/AppFlowy-IO/appflowy-editor/pull/255

Can you help to check the latest code? I tested with Korean IME, it works fine now.

**Comment by voisbe** [comment]
@LucasXu0 It works. Great job! It's much appreciated!
