### ISSUE TITLE
[Bug] The keyboard is not dismissed when the navigator is popped.

### ISSUE THREAD

**Issue by voisbe** [AppFlowy-IO/appflowy-editor#239]
### Bug Description

The keyboard is not dismissed when the navigator is popped.

### How to Reproduce

Try pushing and popping the page with the Appflowy Editor widget.

### Expected Behavior

The keyboard should automatically be dismissed when the navigator is popped, like textfield

### Operating System

iOS

### AppFlowy Editor Version(s)

1.0.4

### Screenshots

'hi' in the first area is a TextField,
The 'good' in the second area is the Appflowy Editor.

https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/2c58e80c-ebf2-4acd-bd66-e5cfb959eace

### Additional Context

Additionally, How do I change the keyboard to dark? If you look at the video, textfield is in dark mode, but appflowy is in light mode.

**Comment by hyj1204** [comment]
Hi @voisbe, 
Can you use the latest code from the main branch to see if the keyboard is still not dismissed?
I cannot reproduce it on my side somehow. 

https://github.com/AppFlowy-IO/appflowy-editor/assets/14248245/5769637b-e09b-4037-b214-1a4925f17b35


Could you share the code if that issue is still there? Thanks

**Comment by voisbe** [comment]
@hyj1204 Looking at the video, it works fine. If you haven't dealt with it, maybe problem #224 on the focusNode side has been resolved and dealt with together. :)

**Comment by voisbe** [comment]
@hyj1204 I found something strange. When I pop the navigation it works fine. However, I don't know if there is any problem in the actual app.. When I restart in vscode, the keyboard stays up.


https://github.com/AppFlowy-IO/appflowy-editor/assets/101335313/44d39de3-9ecf-4e32-bbb2-4f0a399f2414

**Comment by hyj1204** [comment]
Did you dispose the focusNode on this page?
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/14248245/c7035acd-9d4d-4472-a06d-f549210de2da)
like
```
  @override
  void dispose() {
    myFocusNode.dispose();

    super.dispose();
  }
```

**Comment by voisbe** [comment]
@hyj1204 There is no focusnode variable associated with it.

**Comment by hyj1204** [comment]
@voisbe 
Do you have a Discord account to communicate with?  or Is any way I can access your code to debug with it?

**Comment by voisbe** [comment]
The code is nothing special. However, when I tested more, the default TextField also had such a phenomenon. Flutter_quill does too. This doesn't seem to be related to a bug, so I think you can close it. 

```
import 'package:appflowy_editor/appflowy_editor.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      floatingActionButton: FloatingActionButton(
          child: const Icon(Icons.create),
          onPressed: () => Navigator.push(
              context, MaterialPageRoute(builder: (_) => const Editor()))),
      body: const Center(child: Text('test')),
    );
  }
}

class Editor extends StatefulWidget {
  const Editor({super.key});

  @override
  State<Editor> createState() => _EditorState();
}

class _EditorState extends State<Editor> {
  TextEditingController controller = TextEditingController();
  FocusNode focusNode = FocusNode();
  @override
  void dispose() {
    controller.dispose();
    focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          TextField(
            controller: controller,
            focusNode: focusNode,
            autofocus: true,
          ),
          Expanded(
              child: AppFlowyEditor.standard(editorState: EditorState.blank()))
        ],
      ),
    );
  }
}

```
