### ISSUE TITLE
[FR] The text is loaded before it is confirmed.

### ISSUE THREAD

**Issue by ACking-you** [AppFlowy-IO/appflowy-editor#24]
When I type Chinese, unnecessary phonetic characters are loaded before the text is confirmed.
![text](https://user-images.githubusercontent.com/73544345/226803915-75d79f0d-7e7e-4221-84af-39b218e263f5.gif)

**Comment by LucasXu0** [comment]
Hey, @ACking-you. Thanks for reporting. Actually, it's a known issue. I have reported it to Flutter. https://github.com/flutter/flutter/issues/113909#issuecomment-1311478223
