### ISSUE TITLE
[FR] AppFlowy Plugins in AppFlowy Editor

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/appflowy-editor#263]
### Description

The AppFlowy Editor plugin system is great, but there are a lot of plugins in the AppFlowy app that aren't included by default in the AppFlowy Editor package. This would be particularly useful, as many design decisions in AppFlowy Editor are specifically made to accomodate plugins from the main app.
For example, on the line https://github.com/AppFlowy-IO/appflowy-editor/blob/ed75bf61df44281f2605433f8a59460f7417bbc1/lib/src/editor/editor_component/service/renderer/block_component_action.dart#L4 there is a spacing of 50 pixels, which accommodates the action menu plugin in the AppFlowy app, but creates issues when developing plugins solely with AppFlowy Editor, as it creates a 50 pixel gap seemingly out of nowhere. The easiest fix for this seems to just be to use the same plugin that the AppFlowy app does, hence the suggestion of these being built into the editor package.
 
Currently, the seemingly fastest way to get the functionality from the real app into the editor is to copy many of the files from AppFlowy into your own project. It would be quite nice if it was possible to enable some more of these plugins from the default editor, making it easier to implement functionality on par with the main app by using the editor.

### Impact

This change mostly helps developers who would like to implement the features already included in the main AppFlowy app, but are not present in the editor.

**Comment by LucasXu0** [comment]
Let me see how to refactor it and provide a more customizable way.

**Comment by garv-shah** [comment]
thank you!
