### ISSUE TITLE
[Bug] Null is not a subtype of type String url

### ISSUE THREAD

**Issue by MichalNemec** [AppFlowy-IO/appflowy-editor#269]
### Bug Description

On master ed75bf61df44281f2605433f8a59460f7417bbc1
i just tried to select a text and add link to https://foobar.com and got error:
`flutter: [2023-06-30 15:18:59.893011 | Catcher | INFO] type 'Null' is not a subtype of type 'String'`

### How to Reproduce

load up default text you have on readme and try to add link to some text.

### Expected Behavior

produces link as intended

### Operating System

macOS

### AppFlowy Editor Version(s)

master ed75bf61df44281f2605433f8a59460f7417bbc1

### Screenshots

<img width="1417" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/5663019/4a30942e-8795-4813-be53-063ab2d5d60a">

### Additional Context

```
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893390: ------- STACK TRACE -------
flutter: [2023-06-30 15:18:59.893587 | Catcher | INFO] #0      SimpleEditor.textSpanDecor
simple_editor.dart:102
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893587: #0      SimpleEditor.textSpanDecor
simple_editor.dart:102
flutter: [2023-06-30 15:18:59.893645 | Catcher | INFO] #1      SimpleEditor._buildEditor.<anonymous closure>
simple_editor.dart:160
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893645: #1      SimpleEditor._buildEditor.<anonymous closure>
simple_editor.dart:160
flutter: [2023-06-30 15:18:59.893703 | Catcher | INFO] #2      _FlowyRichTextState._textSpan
flowy_rich_text.dart:302
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893703: #2      _FlowyRichTextState._textSpan
flowy_rich_text.dart:302
flutter: [2023-06-30 15:18:59.893755 | Catcher | INFO] #3      _FlowyRichTextState._buildSingleRichText
flowy_rich_text.dart:222
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893755: #3      _FlowyRichTextState._buildSingleRichText
flowy_rich_text.dart:222
flutter: [2023-06-30 15:18:59.893808 | Catcher | INFO] #4      _FlowyRichTextState._buildRichText
flowy_rich_text.dart:203
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893808: #4      _FlowyRichTextState._buildRichText
flowy_rich_text.dart:203
flutter: [2023-06-30 15:18:59.893864 | Catcher | INFO] #5      _FlowyRichTextState.build
flowy_rich_text.dart:86
flutter: [INFO][Catcher]: 2023-06-30 15:18:59.893864: #5      _FlowyRichTextState.build
flowy_rich_text.dart:86
```
its because of the custom text span decor for custom functionality. because it probably takes precedence before all default decorators, i changed it a bit and now href is ignored, whenever i use textSpanDecor.

EDIT: ive changed the function to this, and now its working suddenly. Maybe there is a better way or atleast its noted here if someone has the same troubles.

```
InlineSpan textSpanDecor(TextInsert attributeKey, textSpan, context) {
    final attributes = attributeKey.attributes;
    if (attributes == null) {
      return textSpan;
    }

    if (attributes.containsKey('definition')) {
      ...customFunctionality
    }
    return textSpan;
  }
```

**Comment by LucasXu0** [comment]
Do you mean that you redefine the behavior for the default attribute key, like href?

**Comment by MichalNemec** [comment]
I wanted just to add custom functionality and keep the defaults, what already has been done, like href. With the last edit, it works as intended. Its better to have this noted here, because many people could fall into this problem in the future.
