### ISSUE TITLE
[Bug] shrinkWrap does not work

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/appflowy-editor#271]
### Bug Description

The `shrinkWrap` parameter on `AppFlowyEditor` does not work. If true, the editor should be sized to its contents, but this does not seem to be the case on the latest version.

### How to Reproduce

1. Create an `AppFlowyEditor` widget like normal
2. Set `shrinkWrap` to true
3. Wrap `AppFlowyEditor` in a column

### Expected Behavior

When the steps above are taken, the `AppFlowyEditor` widget should render successfully, as `shrinkWrap` being set to true implies a finite height.
This is particularly needed when in use cases where editors need to be viewed in read-only mode, like normal widgets:
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/7cdcd126-50cc-4b48-81c7-32984f8b8c69)
If I'm not mistaken, the above example does not seem to currently be possible with `AppFlowyEditor`, but should be if the `shrinkWrap` set a finite height.

### Operating System

MacOS

### AppFlowy Editor Version(s)

main branch

**Comment by LucasXu0** [comment]
Did you wrap the editor with a scroll view?

**Comment by garv-shah** [comment]
that worked perfectly! thank you so much, i've been trying to work that out for hours 😭 
thank you thank you :D

**Comment by adnan-nazir** [comment]
Hi @LucasXu0 , Its not working for me as I could not find the wrapper param in the Editor. I am putting this Editor inside a scroll view and facing this exception
`BoxConstraints forces an infinite height.

The offending constraints were: BoxConstraints(w=936.3, h=Infinity)`

I think there should be an option to disable the Editors scroll behavior.

**Comment by adnan-nazir** [comment]
@LucasXu0 can you please provide an example for the dynamic height and focus Node issues?
