### ISSUE TITLE
[Question] Is Importing From Delta Still Possible? 

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/appflowy-editor#273]
### Question

The `DeltaDocumentConvert()` method is depreciated and doesn't seem to be able to convert from Delta to an AppFlowy document anymore, and the Delta import on the example app is yet to be implemented. 
As such, I was wondering if it is still possible to convert Delta JSON to an AppFlowy Editor document.
Thanks!

**Comment by LucasXu0** [comment]
Yes. Let me update the show case in example.

**Comment by LucasXu0** [comment]
@garv-shah  Here's the PR link. https://github.com/AppFlowy-IO/appflowy-editor/pull/277

**Comment by garv-shah** [comment]
thank you so much! :D

**Comment by garv-shah** [comment]
Hi Lucas! Is it possible to get unsupported styles like font-size and font-family to render as the defaults for AppFlowy? Currently, Quill Delta only partially renders and is blank for a majority of the text. Examples are below:

# AppFlowy Currently
<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/2b20a64f-fac7-41b3-9d2e-149a2e9fd63e">

<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/e5ed2873-83a6-4f3e-92f8-0bac2a5fa951">

# Intended Rendering
<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/1ce73da3-5a08-4834-88ca-807f1ec528a2">

<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/756cb02a-4b4c-4a8a-aa87-f3e2cc218833">

Even if it doesn't look the same it would be much better if the text still appears 👍 
Thanks!
