### ISSUE TITLE
[Bug] text with PR #244

### ISSUE THREAD

**Issue by MichalNemec** [AppFlowy-IO/appflowy-editor#275]
### Bug Description

based on this PR: https://github.com/AppFlowy-IO/appflowy-editor/pull/244

whenever i do "d text" and select "d" -> add custom link, then click after text to start writing, it works
whenever i do "doo text" and select "doo" -> add custom link, then click after text to start writing, bugged

### How to Reproduce

write d text -> copy custom logic from the PR -> works
write doo text -> bugging out

### Expected Behavior

can select text however long i want and it doesnt bug out

### Operating System

macOS

### AppFlowy Editor Version(s)

ed75bf6

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/5663019/f5da99fa-97f3-47e4-b207-7553cc1a44e5)

### Additional Context

```
{"insert":"d","attributes":{"definition":"{\"name\": \"Accountability\", \"id\": \"1"}"}},
{"insert":" text and text after -> works\ndoo text\n"},
{"insert":"doo","attributes":{"definition":"{\"name\": \"Accountability\", \"id\": \"1"}"}},
{"insert":" teand text after -> worksxt"}]}},{"type":"paragraph","data":{"delta":[]}}
```

**Comment by LucasXu0** [comment]
Hey, @MichalNemec. If you customize the attributes with a widget span, the text.length should always be 1.

```
{"insert":"doo","attributes":{"definition":"{\"name\": \"Accountability\", \"id\": \"1"}"}},
```

**Comment by MichalNemec** [comment]
Why can't it work the same way as a link you have by default?
Also, could we just possibly add an icon before or after the text?

**Comment by LucasXu0** [comment]
"Because a WidgetSpan is independent, just imagine if your delta is like this: {"insert":"doo","attributes":{"definition":"{\"name\": \"Accountability\", \"id\": \"1\"}"}}, and you render it as an icon or something. Then, if you want to delete it but your text is still 'doo', the system will delete the 'o' instead of 'icon,' which doesn't match the expectation.

Yes, you can add the icon before or after the text, but you still need to define the custom attribute key."

**Comment by MichalNemec** [comment]
as i mentioned in hardcoded colors issue, lets just say you have text foobar and you hook up custom "link" which displays "abrakadabra [icon]", whenever you do backspace, it knows what you are deleting right? it should know that the insert is foobar and delete the whole word. Atleast thats how extended text field works.
