### ISSUE TITLE
[BUG] Scrolling is very hacky and there is no "free" scroll

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#29]
When scrolling in the editor, it's feels a bit hacky due to how the scroll stops the instant you stop scrolling, whereas one would expect it to keep scrolling for a bit, using the "remainder inertia".

<details>
  <summary>Scrolling on MacOS in AppFlowy vs. Notion</summary>

https://user-images.githubusercontent.com/42929161/227020902-4538a00e-cbe6-4a32-988e-c0906d061048.mp4

</details>

**Comment by LucasXu0** [comment]
Yes. I am trying to optimize it.

**Comment by Xazin** [comment]
If you have some ideas on how to improve it (technical), then I might be able to look into it.

**Comment by LucasXu0** [comment]
Actually, I am trying to use `ListView` to render the data now.

**Comment by jenishMyTechnology** [comment]
@LucasXu0 any update when i can expect scroll to bottom automatically ?

**Comment by LucasXu0** [comment]
Hey, @jenishMyTechnology. It's related to this [PR](https://github.com/AppFlowy-IO/AppFlowy/pull/2118). Since it's a huge job, I think I would finish it in next week.
