### ISSUE TITLE
[FR] Provide a way to customize link behavior and update the documentation related to theme

### ISSUE THREAD

**Issue by LucasXu0** [AppFlowy-IO/appflowy-editor#292]
### Description

* remove the default link behavior 
* provide a way to customize the link behavior
* update the theme docuementation

### Impact

For the developers who want to customize the link.

### Additional Context

Related to https://github.com/AppFlowy-IO/appflowy-editor/issues/211#issuecomment-1621631167

**Comment by Xazin** [comment]
Wouldn't it be enough to support eg.

- When inserting anything that contains a link, then insert it as a link
- When inserting a link on text, then add the link to the selection
- When inserting a link from the slash menu, ask for both a link and a link text

And if we're talking about supported URLs, we can, of course, expand that to allow developers to accept more than HTTP/HTTPS, eg. FTP, MAILTO, etc.

Am I missing something?

**Comment by LucasXu0** [comment]
> Wouldn't it be enough to support eg.
> 
> * When inserting anything that contains a link, then insert it as a link
> * When inserting a link on text, then add the link to the selection
> * When inserting a link from the slash menu, ask for both a link and a link text
> 
> And if we're talking about supported URLs, we can, of course, expand that to allow developers to accept more than HTTP/HTTPS, eg. FTP, MAILTO, etc.
> 
> Am I missing something?

What I meant is to disable the default behavior for href text. For instance, some developers may not want the link menu to appear when tapping the href text and instead prefer to customize its gesture behavior.

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/pull/293
