### ISSUE TITLE
[Bug] Cant able to locate the cursor after image uploading

### ISSUE THREAD

**Issue by Chandu-bs** [AppFlowy-IO/appflowy-editor#295]
### Bug Description

I can't locate the cursor once the image is uploaded through URL.

The thing I identified is focusNode is not working after upload.

Issue 2: The Image uploaded has the top and bottom padding or space, where we can't locate the cursor.

### How to Reproduce

Cursor should locate properly, after the image upload!

### Expected Behavior

Cursor should locate properly, after the image upload!

### Operating System

Windows

### AppFlowy Editor Version(s)

1.0.4

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/98700279/22bbf6f0-bbb9-4f2e-a96f-5a3f8c6bb386

**Comment by LucasXu0** [comment]
@Chandu-bs Thanks for reporting. I will provide some basic rules to avoid this issue.

Here's the sample what I implemented in AppFlowy.

```dart
  Future<void> applyRules() async {
    ensureAtLeastOneParagraphExists();
    ensureLastNodeIsEditable();
  }

  Future<void> ensureLastNodeIsEditable() async {
    final editorState = this.editorState;
    if (editorState == null) {
      return;
    }
    final document = editorState.document;
    final lastNode = document.root.children.lastOrNull;
    if (lastNode == null || lastNode.delta == null) {
      final transaction = editorState.transaction;
      transaction.insertNode([document.root.children.length], paragraphNode());
      await editorState.apply(transaction);
    }
  }

  Future<void> ensureAtLeastOneParagraphExists() async {
    final editorState = this.editorState;
    if (editorState == null) {
      return;
    }
    final document = editorState.document;
    if (document.root.children.isEmpty) {
      final transaction = editorState.transaction;
      transaction.insertNode([0], paragraphNode());
      transaction.afterSelection = Selection.collapse([0], 0);
      await editorState.apply(transaction);
    }
  }
```

**Comment by Chandu-bs** [comment]
Soo these should be implemented, while pressing the upload button??

**Comment by Chandu-bs** [comment]
Hey @LucasXu0 , want to ask one more thing, how can we convert a widget into a node and can insert in editor. Hoping for a reply.
Thanks!

**Comment by LucasXu0** [comment]
> Soo these should be implemented, while pressing the upload button??

No, I meant that we can provide some basic rules to prevent the issues you submitted. For instance, we can utilize the ensureLastNodeIsEditable function to ensure that there is always an editable node at the end of the document.

**Comment by LucasXu0** [comment]
Why do you mean by 'converting a widget into a node'? Do you want to define a node with a new type?

**Comment by Chandu-bs** [comment]
Yes i want to define a node with new type, but doccumentation is not helping up. Simply i want to insert a widget into the editor, so for that we need to make a nodebuilder for that widget right??.. So how can i start for this.. Any thing that could help please.
Thanks!

**Comment by LucasXu0** [comment]
Here's an example for math equation block. You can refer to it first. I plan to add/update the documentation about customizing block this week.

**Comment by Chandu-bs** [comment]
Thank you. Will be waiting for the example and doccumentation.

**Comment by LucasXu0** [comment]
FYI, Just update the previous comment with the link.

**Comment by Chandu-bs** [comment]
Hey, hi @LucasXu0. Can you please tell us where we can use the rules you mentioned before and how we can implement a basic example code? 
Thanks!
