### ISSUE TITLE
[Question] Difficulty with slashmenu

### ISSUE THREAD

**Issue by jessicamrbr** [AppFlowy-IO/appflowy-editor#299]
### Bug Description

Slashmenu not behaving as it should.

### How to Reproduce

I type some text in the paragraph block type, access the menu and choose the transform to header, nothing happens

### Expected Behavior

The conversion of the type of block is expected, according to the choice in the menu.

### Operating System

macos, chrome

### AppFlowy Editor Version(s)

appflowy_editor: ^1.1.0

### Screenshots

![Screenshot 2023-07-11 at 02 58 01](https://github.com/AppFlowy-IO/appflowy-editor/assets/18180548/bc665bb6-be5f-4822-8cb8-00e9e2147e85)

**Comment by LucasXu0** [comment]
Hi, @jessicamrbr. Thanks for reporting. I have submitted a PR to fix it.
