### ISSUE TITLE
[Bug]  Toolbar Item Tooltips are too responsive

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#302]
### Bug Description

The tooltips of toolbar items pop up way too fast. 

It's normal for there to be a short delay, the way it is now it is instant which causes the tooltip behavior when hovering over items in the menu a bit overkill.

https://github.com/AppFlowy-IO/appflowy-editor/assets/42929161/91fb4229-8d19-42ba-8bc4-531e06e4e5e0

### How to Reproduce

1. Make a selection
2. Hover over items in the toolbar
3. Tooltip is instantly shown, even for those which you didn't intend to view tooltip for

### Expected Behavior

1. Make a selection
2. Hover over items in the toolbar
3. If hovered for more than # MS then show tooltip

### Operating System

MacOS, Windows

### AppFlowy Editor Version(s)

main

**Comment by LucasXu0** [comment]
> Hi @Xazin , I have created PR for this bug, can you assign me to this issue and review my PR? Thank you
> 
> #315
> 
> cc @LucasXu0

Sure.

**Comment by andynvt** [comment]
how to enable this menu on web?
