### ISSUE TITLE
[FR] Support drag selection handlers - When long pressing a word it is selected, it should be possible to drag the left or right part of the selection to expand it

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#308]

**Comment by alihassan143** [comment]
#228

**Comment by alihassan143** [comment]
@LucasXu0  what is the status of this issue
any plans on this?

**Comment by Xazin** [comment]
> @LucasXu0  what is the status of this issue
> 
> any plans on this?

There is already an open PR that closes this issue.

See #354
