### ISSUE TITLE
[FR] Support character commands to be triggered by several characters

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#326]
### Description

We should support several characters to trigger the same shortcut command.

### Impact

Improved way of binding multiple characters to the same handler.

**Comment by LucasXu0** [comment]
@Xazin Is it still in the plan, or else I will close it?

**Comment by Xazin** [comment]
> @Xazin Is it still in the plan, or else I will close it?
> 
> 

I still plan to look at it, but it's not a priority after your refactor. I will close this for now and create it if I reach that far down on my todos. 😂
