### ISSUE TITLE
[Bug] Desktop color picker issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#339]
### Bug Description

1、desktop color picker Display screen at specific location
2、Custom color Difficulty in triggering editing
3、Custom color Hex value display error

### How to Reproduce

Simply select the text color operation

### Expected Behavior

The operation floating window is fully displayed on the screen and the operation display is normal

### Operating System

desktop

### AppFlowy Editor Version(s)

master

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/06278eed-e38f-404d-82c2-2db9b61d95e9)
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/f7e9a85b-4e1d-47a3-a482-668cf194d18e)

**Comment by LucasXu0** [comment]
<img width="1439" alt="Screenshot 2023-07-25 at 15 40 29" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/02c08105-f0a1-404a-a06a-c76646a836bc">
<img width="1439" alt="Screenshot 2023-07-25 at 15 40 45" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/e71af66d-6571-4a29-9712-cf5b54f05b9e">

@q200892907, I didn't reproduce on the latest main branch.

**Comment by q200892907** [comment]
@LucasXu0 在一个临界的值的附近会出现无法显示全的问题

**Comment by q200892907** [comment]
#341 Modified the calculation value, 200->250, 250 is the height of ColorPicker

**Comment by q200892907** [comment]
@LucasXu0 
3、Custom color Hex value display error

Select a color first, and then go to the custom color view
