### ISSUE TITLE
[FR] Skip whitespace between words while navigating with CTRL+ARROW keys

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/appflowy-editor#344]
### Description

Pressing CTRL+ARROW keys to navigate between words (ALT + ARROW keys on Mac) should skip whitespace between words.

### Impact

All users who use the shortcut for navigating between words.

### Additional Context

One can refer to the implementation of the CTRL+Backspace key to check how can the whitespace be skipped.

**Comment by johansutrisno** [comment]
Hi @LucasXu0 , can you assign me to this issue? 
this is my current progress

https://github.com/AppFlowy-IO/appflowy-editor/assets/22239637/cd978a42-eb2e-4414-8970-98da32de581c

**Comment by johansutrisno** [comment]
I have created the PR for this issue, please review it, thank you  🙏🏻
https://github.com/AppFlowy-IO/appflowy-editor/pull/363
