### ISSUE TITLE
[Bug] Quill Delta Import

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/appflowy-editor#356]
### Bug Description

Hi There! Currently, certain Quill Delta strings do not render correctly at all. For example:

```
[{"insert": "How many digits are there in the smallest number which is composed entirely of fives (e.g.5555) and which is divisible by 99?"}]
```

This is simply a normal sentence, but it does not seem to render without an attribute tag. As mentioned in https://github.com/AppFlowy-IO/appflowy-editor/issues/273#issuecomment-1617569699, certain styles such as font-size and font-family are unsupported, but could it be possible to render these as the defaults for AppFlowy? Currently, Quill Delta only partially renders and is blank for a majority of the text. Examples screenshots are below:

# AppFlowy Currently
<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/2b20a64f-fac7-41b3-9d2e-149a2e9fd63e">

<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/e5ed2873-83a6-4f3e-92f8-0bac2a5fa951">

# Intended Rendering
<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/1ce73da3-5a08-4834-88ca-807f1ec528a2">

<img width="817" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/64292655/756cb02a-4b4c-4a8a-aa87-f3e2cc218833">

Even if it doesn't look the same it would be much better if the text still appears 👍 
Thanks!

### How to Reproduce

Follow the example [here](https://github.com/AppFlowy-IO/appflowy-editor/pull/277#issue-1785565324) with the input Quill Delta of `[{"insert": "How many digits are there in the smallest number which is composed entirely of fives (e.g.5555) and which is divisible by 99?"}]`.

### Expected Behavior

Please see above

### Operating System

MacOS, iOS, Web

### AppFlowy Editor Version(s)

main branch

### Screenshots

Please see above

**Comment by LucasXu0** [comment]
@garv-shah Fixed in https://github.com/AppFlowy-IO/appflowy-editor/pull/366.

I didn't handle the single line case before.

**Comment by garv-shah** [comment]
@LucasXu0 just tried it on the latest commit and it still didn't seem to render the text with the example I provided above. Does the example work for you?
