### ISSUE TITLE
[Bug] Image Upload Doesn't Work on Web

### ISSUE THREAD

**Issue by garv-shah** [AppFlowy-IO/appflowy-editor#364]
### Bug Description

When picking an image on the web using appflowy-editor, the following error is recieved:

```
Error: Exception: You are setting a type [FileType.image]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49 
```
 This greats traced back to the following line `packages/appflowy_editor/src/editor/block_component/image_block_component/image_upload_widget.dart 285:44` and seems to be an error with permissions to pick files on the web.

### How to Reproduce

Create an editor and run it on the web. Try to insert an image and it won't work.

### Expected Behavior

For the image to be inserted

### Operating System

Web

### AppFlowy Editor Version(s)

main

**Comment by LucasXu0** [comment]
Only the network image is supported on the Web platform now.

**Comment by garv-shah** [comment]
@LucasXu0 would you be happy for me to submit a PR to try and fix this?

**Comment by LucasXu0** [comment]
Sure. I appreciate your help.

**Comment by garv-shah** [comment]
@LucasXu0 Hi Lucas! I made a PR which fixes image upload on the web, at least for me. It probably won't pass the automated tests for code coverage, would it be possible for you to format the PR? Thanks!
