### ISSUE TITLE
The non-abstract class '_AppFlowyInputState' is missing implementations for these members:

### ISSUE THREAD

**Issue by asadamatic** [AppFlowy-IO/appflowy-editor#37]
I got this error when running the app on an IOS simulator.

```
Error (Xcode): ../../.pub-cache/hosted/pub.dev/appflowy_editor-0.1.4/lib/src/service/input_service.dart:60:7: Error: The non-abstract class '_AppFlowyInputState' is missing implementations for these members:

Could not build the application for the simulator.
Error launching application on iPhone 14 Plus.
```

**Comment by RomanIvn** [comment]
fork and change to:
class _AppFlowyInputState extends State<AppFlowyInput>
  **with TextInputClient**
    implements AppFlowyInputService, DeltaTextInputClient {
 
in lib/src/services/input_service.dart
untill this lib is updated

**Comment by MayurSMahajan** [comment]
Which flutter version are you using currently?

**Comment by asadamatic** [comment]
`Flutter (Channel master, 3.8.0-14.0.pre.3`

**Comment by MayurSMahajan** [comment]
cc: 
@rileyhawk1417 can you please take a look here

**Comment by rileyhawk1417** [comment]
@asadamatic are you trying to build AppFlowy for IOS?

**Comment by asadamatic** [comment]
Yes, I was testing it on an ios simulator, running IOS 16.2.

**Comment by rileyhawk1417** [comment]
Flowy Editor should just work on its own as a flutter package.
Best to ask @LucasXu0 I haven't ran FlowyEditor on IOS before.

**Comment by MayurSMahajan** [comment]
Thanks @rileyhawk1417

**Comment by annieappflowy** [comment]
@asadamatic , appflowy_editor has not supported mobile yet. We're developing it at the moment and should be released by June. You can have a try on Windows or MacOS and let us know if you run into issues.
