### ISSUE TITLE
[Bug] Checkbox unresponsive in custom Theme example in editor example app

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/appflowy-editor#372]
### Bug Description

![ezgif com-video-to-gif (4)](https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/feb8191a-64a7-4081-82b5-53a807220c57)

In custom theme example of the editor , the checkbox is unresponsive to clicks

### How to Reproduce

- Run the example app of AppFlowy Editor 
- Go to side navigation bar and select custom color theme
- try to click on checkbox

### Expected Behavior

The checkbox should be responsive to clicks

### Operating System

MacOs

### AppFlowy Editor Version(s)

1.2.3

**Comment by LucasXu0** [comment]
Closed as completed.
