### ISSUE TITLE
[FR] The Context menu should have commands displayed along with the text 

### ISSUE THREAD

**Issue by Mukund-Tandon** [AppFlowy-IO/appflowy-editor#377]
### Description

The context menu should look something like -
<img width="178" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/b2c35b86-db85-4bf1-bffc-c971c55ac17b">

Current - 
<img width="131" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71614009/a50b0dba-6b22-4c45-8a75-3f6bca23e343">

### Impact

It will be visually better for users

### Additional Context

I think Its a good first issue

**Comment by LucasXu0** [comment]
The context menu is customizable. You can create your own `ContextMenuItem`.
