### ISSUE TITLE
[Bug] Strikethrough is not pasted when more than 3 styles (bold, underline, italic) are applied

### ISSUE THREAD

**Issue by MayurSMahajan** [AppFlowy-IO/appflowy-editor#381]
### Bug Description

Strikethrough is not pasted when more than 3 styles (bold, underline, italic) are applied](https://forum.appflowy.io/t/strikethough-is-not-pasted-when-more-than-3-styles-bold-underline-italic-is-applied/59)

### How to Reproduce

1. Open AppFlowy Editor
2. Type or paste a line of text.
3. Select this text and apply Bold, Underline, Italic and Strikethrough
4. Copy this line and Paste it

### Expected Behavior

Strikethrough should also be copy pasted 

### Operating System

Windows 11

### AppFlowy Editor Version(s)

latest main

### Screenshots

![strikethrough](https://github.com/AppFlowy-IO/appflowy-editor/assets/47064215/0ddfe29e-042b-4fb1-9d4c-72df47a006f3)

**Comment by Mukund-Tandon** [comment]
text color and highlight also have  a  issue - https://forum.appflowy.io/t/copy-paste-in-editor-showing-unusual-behaviour-when-the-portion-copied-has-text-color-or-highlight-color/55

I would like to work on this

**Comment by alihassan143** [comment]
@MayurSMahajan  i fixed this issuee now creating pr
