### ISSUE TITLE
[FR]: Adding an ability to have a link check before embedding

### ISSUE THREAD

**Issue by yatendra2001** [AppFlowy-IO/appflowy-editor#382]
### Description

There should be a mechanism to check whether the inserting text is in a valid link format. I think we can use regex for link validation.

![gif](https://global.discourse-cdn.com/standard11/uploads/appflowy/original/1X/d5d27e1daf1a762a5b5b5859071c33470da6cded.gif)

## Ideal Behaviour

![ideal gif](https://global.discourse-cdn.com/standard11/uploads/appflowy/original/1X/af2cfa6cb153205787c6b95ec4ec8f6c4bc0c0cc.gif)

### Impact

Users will make fewer mistakes while embedding the link hence creating a reliable ecosystem.

**Comment by johansutrisno** [comment]
Hi @LucasXu0 and @Xazin I have added the feature for validate the link, could you please assign me to this issue and review the PR? Let me know if you have any suggestion. Thank you very much.

**Comment by LucasXu0** [comment]
closed as completed.
