### ISSUE TITLE
[Bug]: Active hover on upload image

### ISSUE THREAD

**Issue by yatendra2001** [AppFlowy-IO/appflowy-editor#384]
### Bug Description

There must be some sort of ative hover when user try to upload image.

![bug-gif](https://global.discourse-cdn.com/standard11/uploads/appflowy/original/1X/ac92932aec46bc03e3e591f4305b4b4008ecfdba.gif)

### How to Reproduce

1. open editor
2. type `/` and select image
3. try to hover over image.

### Expected Behavior

![ideal-gif](https://global.discourse-cdn.com/standard11/uploads/appflowy/original/1X/d830f2fa7332a136fc66f7b6a3f9d732dadb678e.gif)

### Operating System

MacOS

### AppFlowy Editor Version(s)

main

### Additional Context

related to: #368

**Comment by johansutrisno** [comment]
Hi @LucasXu0 and @Xazin  I have resolved this issue in this PR https://github.com/AppFlowy-IO/appflowy-editor/pull/597, could you please assign me to this issue and review that PR?

Let me know if you have any concern.

Thank you.

**Comment by MayurSMahajan** [comment]
@yatendra2001 this issue can be closed.

**Comment by yatendra2001** [comment]
yes ser issue closed 🫡
