### ISSUE TITLE
[Bug] replace does not work in certain use-cases

### ISSUE THREAD

**Issue by squidrye** [AppFlowy-IO/appflowy-editor#39]
### Bug Description

This issue was discovered in appflowy, so I have used a usecase there to describe the issue.

As the title suggests, replace option when using OpenAi to generate a summary or fix-spelling does not work as expected in few use-cases, if response generated is multiline, last line overwrites the previous lines. This can cause much problem and confusion if user is working on large selections of text for correction or summary generation.

### How to Reproduce

1. Select some text on editor (likely a query to generate multiple lines from open ai)
2. select summarize and then replace the selected text.

### Expected Behavior

Selected text should be correctly replaced by the response generated by open-ai.

### Operating System

Linux

### AppFlowy Version(s)

Version 0.1.1 (1)

### Screenshots

https://user-images.githubusercontent.com/84044317/227204772-9077f453-4994-41da-9618-5ae431cac55e.mp4

### Additional Context

This issue was previously opened, resolved and merged in appflowy and I needed it to write correct integration tests for other dependent issue I was working on however, since dependencies there have been changed for appflowy editor, those fixes are now redundant. For more reference kindly take a look at these.

https://github.com/AppFlowy-IO/AppFlowy/pull/2100 (Now Redundant)
https://github.com/AppFlowy-IO/AppFlowy/pull/2107#issuecomment-1496291314

These changes will be tested in appflowy via integration tests.

**Comment by squidrye** [comment]
Let me know if I have permission to open pr's to fix this issue so that I can finish up with main issues on appflowy

**Comment by LucasXu0** [comment]
Hey, @squidrye. I remember you fixed this issue before in the AppFlowy repository. I just synced the code here. Could you help me check if it works perfectly now?

**Comment by squidrye** [comment]
Hi @LucasXu0, I'll check it out and revert back, also could you add another change in transaction.dart, I need this for selection to work correctly, issue was if some node in document is deleted beforeSelection is not being propagated to afterSelection , I'll link the commit here for a review [Commit in other repo](https://github.com/AppFlowy-IO/AppFlowy/pull/2107/commits/eeacd872bb3e4f89d60c3775c2aebdff370cc502)
