### ISSUE TITLE
[Bug] Cursor selection blinking after back press event for the math equation block

### ISSUE THREAD

**Issue by Chandu-bs** [AppFlowy-IO/appflowy-editor#394]
### Bug Description

The selection is blinking after deleting the node for few seconds, not knowing why exactly this.
The back space event is working properly, for image upload but same code has been used for this.

### How to Reproduce

Need to remove the blinking effect after deletion.

### Expected Behavior

Selected area shouldn't blink after the deletion of node after pressing back button.

### Operating System

Windows

### AppFlowy Editor Version(s)

1.2.2

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/98700279/8a2e0a83-da3a-4e49-9f25-994e39b9402d

**Comment by LucasXu0** [comment]
@Chandu-bs Did you customize a block component for the math equation? I think it's related to the `cursorStyle` you defined.
