### ISSUE TITLE
[Bug] Find and Replace fails on certain usecase

### ISSUE THREAD

**Issue by squidrye** [AppFlowy-IO/appflowy-editor#396]
### Bug Description

Find and replace fails when words to be replaced are placed one after another, sometimes this kind of replacement would freeze the entire editor, user won’t be able to work unless they restart the editor, I couldn’t reproduce the scenario where editor froze with every test but it happens quite frequently.

### How to Reproduce

1. Type in following sequence of word
> aaaa
2. Find ‘a’
3. Replace with word of length > 1
4. For eg if replaced by ‘test’
> tttteststststaaa

### Expected Behavior

found words should be correctly replaced by target word

### Operating System

Arch Linux

### AppFlowy Editor Version(s)

1.2.2

### Screenshots

![ezgif com-video-to-gif (1)](https://github.com/AppFlowy-IO/appflowy-editor/assets/84044317/66d3fde6-c19e-4582-8eb4-8ec218bbe445)

**Comment by Xazin** [comment]
Hey @MayurSMahajan will you work on this?

The bug occurs from inside `replaceSelectedWord`.

**Comment by MayurSMahajan** [comment]
I will work on this. I was on a vacation for a couple of days.
