### ISSUE TITLE
cmd + backspace deletes word instead of all text to the beginning of the line

### ISSUE THREAD

**Issue by simonbengtsson** [AppFlowy-IO/appflowy-editor#4]
Noticed a minor difference to native and web text fields - `cmd + backspace` deletes a word instead of all text to the beginning of the line. Is it something that would be open for me to contribute a fix for? Potentially complex, but thought I could at least look into it.

Other than that the only thing I noticed is that the menu does not work on my keyboard (discussed here https://github.com/AppFlowy-IO/AppFlowy/issues/1876). Not a big of a deal however since all the menu options are possible to reach by other means such as writing #  for a header etc. Keyboard navigation, keyboard selection, triple click to select row, double click to select word - all supported. Really awesome!

**Comment by LucasXu0** [comment]
Hey, @simonbengtsson. Sure. I assigned it to you.

I registered the shortcut `cmd + backspace` as deleting a word. I suggest you can register the shortcut `cmd + shift + backspace` as deleting a word, and the shortcut `cmd + backspace` as deleting a sentence.

<img width="711" alt="Screenshot 2023-03-09 at 16 09 31" src="https://user-images.githubusercontent.com/11863087/223959958-d4a3e8ba-b61f-46f4-aabc-a8f36637fb91.png">

**Comment by Xazin** [comment]
I guess it depends on Platform no?

On Windows, the default behavior is deleting a word, on MacOS (and I'm assuming Linux & Ubuntu) it's indeed different.

So do we want to enforce one behavior (no matter which one you pick, it will be wrong), or both behaviors?

**Comment by Xazin** [comment]
@simonbengtsson If you need help let me know.

I managed to implement the shortcut command itself yesterday, feel free to cherry-pick the commit and work from there.

Otherwise I can also write a test and make the PR.

Commit: https://github.com/Xazin/appflowy-editor/commit/457c14cba26e8e648325906fc9368cf223a23d86

**Comment by simonbengtsson** [comment]
Awesome! I've yet to start so feel free to submit it 👌
