### ISSUE TITLE
[Bug] Copy/paste broken on macOs, half broken on Web

### ISSUE THREAD

**Issue by stefanosiano** [AppFlowy-IO/appflowy-editor#411]
### Bug Description

Copy:
On macOs, when i copy the text inside the editor (either Cmd+c or right click -> copy) nothing is copied.
On web, Cmd+c doesn't work at all, while right click -> copy copies the text, and I'm able to paste it as rtf on other platforms (like google docs), so this way it works.

Paste:
On macOs, it just doesn't work.
On web, cmd+v copies the text without any formatting, while right click -> paste pastes the text with no new lines and bold, ignoring any formatting.

Copying and pasting on the web inside the editor works, but only if copying and pasting through the context menu. Cmd+c doesn't work and cmd+v pastes without formatting.

Web in this case means Google Chrome

### How to Reproduce

just use default widget `AppFlowyEditor(editorState: editorState)`

### Expected Behavior

cmd+c and cmd+v work the same way as right click and "copy" and "paste".
Pasting some rtf text (from inside or outside of the editor) preserves formatting

### Operating System

MacOs, Web

### AppFlowy Editor Version(s)

1.2.3

**Comment by LucasXu0** [comment]
@stefanosiano, I can't reproduce the issue you mentioned on macOS. There're copy-paste tests in this repo, and the CI didn't raise any errors.

**Comment by stefanosiano** [comment]
restarted the whole ide and flutter app, and now it seems to work.
There is still some issues, trying to copy a code from the ide into the editor makes it go crazy (no parenthesis, commas replaced with newlines, missing words after `$` or `@`), but in all other cases, like copying pasting from google docs, github, etc. it works fine now.
Maybe it's something related to background color? I've seen there is already [an issue](https://github.com/AppFlowy-IO/appflowy-editor/issues/388) for that

**Comment by MayurSMahajan** [comment]
Hey @stefanosiano! Glad things are working now. Could you please elaborate on "trying to copy a code from the ide ..." and create a new issue for it? Please also include the code you are trying to paste. Thank you!
