### ISSUE TITLE
[Bug] Keyboard shorcuts for bold, underline and italics don't work without selecting text.

### ISSUE THREAD

**Issue by Chandan-CV** [AppFlowy-IO/appflowy-editor#416]
### Bug Description

Keyboard shortcuts for bold, underline and italics (cmd+b, cmd+u, cmd+i) works fine when some text is selected. It applies the formatting on the selected text and continues the same formatting unless specified otherwise. But you cannot get it to work without selecting any text.

just pressing ctrl + b does nothing. We need to select some text for it to work.

### How to Reproduce

1. Open Appflowy (the editor)
2. type something anywhere
3. select some text
4. press ```cmd + b``` 
5. the selected text becomes bold
6. The next thing you type is still bold
7. You cannot disable this by pressing ``` cmd + b``` again
8. You need to select text again and press ```cmd+b``` to do so.

### Expected Behavior

We should be able to toggle these three features without selecting the text

### Operating System

Ubuntu 22.04.2 LTS

### AppFlowy Editor Version(s)

1.2.3 (Appflowy 0.3.0)

### Screenshots

![Screenshot from 2023-08-25 17-32-54](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/a67c9e02-58b9-4644-901e-078758661da2)
![Screenshot from 2023-08-25 17-33-05](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/fcb1bfa7-15fd-4dba-99b1-86e59da31e4b)
![Screenshot from 2023-08-25 17-33-47](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/d8cc8a15-fe7a-40f8-9a10-38ca71a63e88)
![Screenshot from 2023-08-25 17-34-41](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/af7bd40a-2205-4fe4-9355-25dd8f0d434c)
![Screenshot from 2023-08-25 17-35-06](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/48d20020-71ad-4ecb-9a07-cd92de58089c)
![Screenshot from 2023-08-25 17-35-40](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/80c7cf32-d3e6-4e8d-88c3-64456a49ac34)

**Comment by Chandan-CV** [comment]
@LucasXu0 @annieappflowy, if no one is working on this issue, can I take it up?

**Comment by Xazin** [comment]
> @LucasXu0 @annieappflowy, if no one is working on this issue, can I take it up?

For now I have assigned you, seems no one is currently working on this.

**Comment by LucasXu0** [comment]
@Chandan-CV Please share your idea here before coding and feel free to let me know if you need any help.

Two scenarios have come to mind:

- Select some text, format it, and then continue typing more text. The newly inputted text should not adopt the formatting applied earlier.
- When nothing is currently selected, press Cmd/Ctrl + the formatting shortcut to format the upcoming text. Pressing the shortcut again should keep the newly inputted text in its normal style.

**Comment by Chandan-CV** [comment]
@LucasXu0 I was thinking to keep it as similar to the other platforms out there like (google docs, ms-word, etc)

- When text is selected and a formatting shortcut is pressed, The selected text gets formatted. The newly entered text will take the formatting of the text right before it.
- When nothing is selected and a formatting shortcut is pressed, The newly entered text since that point will be formatted accordingly, and the same happens when it's pressed again. 


I was thinking first I will fix the "no selection + formatting shortcut pressed", that would make it easier to use the formatting shortcuts. Then I will finish up selection part and formatting only the selected part.

Thank you for responding to my issue and your help is greatly appreciated :)

Thank you!

**Comment by Chandan-CV** [comment]
@LucasXu0 @Xazin A tiny update on the progress. Most of the functions used for formatting keyboard shortcuts need the ```selection.length>0```. So I am overriding those functions to accommodate for toggle without any selection. Till now, I am able to find only one workaround,
1. when a shortcut is pressed, let's say ```cmd+b```
2. it adds a white space by: ```insertTextAtCurrentPosition(" ");```
3. then automatically selects the white space
4. then formats it accordingly
5. the texts entered after this carries formatting expected.

I am sharing this as an update. I am figuring out ways to achieve this without leaving a blank space when a shortcut executed.
Any inputs here would be appreciated greatly :)
[Screencast from 05-09-23 10:07:57 PM IST.webm](https://github.com/AppFlowy-IO/appflowy-editor/assets/37525954/2d257552-39f8-4b07-902e-ebd7b91c87f7)

**Comment by Xazin** [comment]
Closing this as Lucas implemented a solution based on the above PRs
