### ISSUE TITLE
[FR] table plugin html encoder and decoder

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#426]
### Description

it enable copy and paste table in HTML plugin 

### Impact

it will  make editor more compatible with all platforms

**Comment by LucasXu0** [comment]
Yes. Support pasting table from the other platforms will be great.

**Comment by alihassan143** [comment]
@LucasXu0 wiil you assign this to me i almost done in decode code

**Comment by LucasXu0** [comment]
Closed as completed.
