### ISSUE TITLE
[Bug] text alignment should follow the block alignment

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#428]
### Bug Description

When we use alignment of block the text did not follow the block alignment 
<img width="1636" alt="Screenshot 2023-08-29 at 4 35 04 PM" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/c3f7c941-52ab-49f3-bdbd-b400347a6459">

if block aligns center the rich text should be align center

### How to Reproduce

apply alignment on block and start writing text the text follows the right alignment

### Expected Behavior

Text should also be center or left or right according to block alignment

### Operating System

All

### AppFlowy Editor Version(s)

main branch

**Comment by LucasXu0** [comment]
Nice catch! I will fix it later.
