### ISSUE TITLE
Can add a attr readOnly for read？

### ISSUE THREAD

**Issue by xiaodusx1** [AppFlowy-IO/appflowy-editor#436]
And can save as pdf file.

**Comment by alihassan143** [comment]
@xiaodusx1  you can pass read-only parameter in editor state to view only
to save pdf [HtmlTopdf](https://pub.dev/packages/htmltopdfwidgets) you can this package 
its uses same converter as appflowy

**Comment by xiaodusx1** [comment]
> @xiaodusx1 you can pass read-only parameter in editor state to view only to save pdf [HtmlTopdf](https://pub.dev/packages/htmltopdfwidgets) you can this package its uses same converter as appflowy

thank you so much.

**Comment by xiaodusx1** [comment]
> @xiaodusx1 you can pass read-only parameter in editor state to view only to save pdf [HtmlTopdf](https://pub.dev/packages/htmltopdfwidgets) you can this package its uses same converter as appflowy

htmltopdfwidgets don't support Simplified Chinese？：
flutter: Unable to find a font to draw "拼" (U+62fc) try to provide a TextStyle.fontFallback
flutter: Unable to find a font to draw "晾" (U+667e) try to provide a TextStyle.fontFallback
flutter: Unable to find a font to draw "晒" (U+6652) try to provide a TextStyle.fontFallback
flutter: Unable to find a font to draw "意" (U+610f) try to provide a TextStyle.fontFallback

**Comment by at15** [comment]
For people who found this issue, you cannot set `editable` on the `EditorState` directly, seems it will get overwritten by the one on `AppFlowyEditor`

Wrong way

```dart
viewerState = EditorState(document: Document.fromJson(...));
viewerState.editable = false;
```

Right way

```dart
AppFlowyEditor(
      editorState: viewerState,
      editable: false,
      editorStyle: const EditorStyle.mobile(),
)
``` 

https://github.com/AppFlowy-IO/appflowy-editor/blob/1ceed9b4d21033673fc8c3142f9d1742b7c15dac/lib/src/editor_state.dart#L279-L288
