### ISSUE TITLE
[FR] Want to add mobile and web versions of math equation and also mobile version of image

### ISSUE THREAD

**Issue by Chandu-bs** [AppFlowy-IO/appflowy-editor#446]
### Description

Will update a PR for the following things!

### Impact

Math equation and mobile version of image

**Comment by Chandu-bs** [comment]
hey @LucasXu0 , how can i update a PR branch regarding this!

**Comment by LucasXu0** [comment]
@Chandu-bs Are you still working on it?

**Comment by Chandu-bs** [comment]
Yup, will update by this weekend!

**Comment by LucasXu0** [comment]
The image block and math equation block are supported. Closed as completed.
