### ISSUE TITLE
[Bug] Multiple cursor on mobile

### ISSUE THREAD

**Issue by dggbond** [AppFlowy-IO/appflowy-editor#455]
### Bug Description

There is double cursor on mobile editor.
![output](https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/49233600-c050-4248-bd6c-e4af62cb4025)

### How to Reproduce

just run example on any iphone device.

### Expected Behavior

only one cursor and current position.

### Operating System

IOS

### AppFlowy Editor Version(s)

95e111983a0353db3db2c8f7e8b7970a637f3bbc

### Screenshots

![output](https://github.com/AppFlowy-IO/appflowy-editor/assets/37775224/9d79d5bc-1c26-4680-8f9a-d7f13489a2d0)

**Comment by LucasXu0** [comment]
Hi, @dggbond. The mobile platform isn't stable in the main branch now. Please check the latest tag, 1.3.0.
