### ISSUE TITLE
[Bug] Additional spaces on top of node

### ISSUE THREAD

**Issue by Chandu-bs** [AppFlowy-IO/appflowy-editor#460]
### Bug Description

An additional space observed on top of the node (math equation), that too when there is any text or node before the equation. If it is a blank document and the equation is the first to be typed, then no space is observed.

### How to Reproduce

Need to know how to remove the space at certain path needed

### Expected Behavior

Spaces should be removed on top of the node 

### Operating System

Windows

### AppFlowy Editor Version(s)

1.2.2

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/98700279/11e87bbf-ad23-4322-8352-4a7ff89bd1b4

**Comment by LucasXu0** [comment]
Could you provide the code to demonstrate how to insert a math equation?
