### ISSUE TITLE
[FR] Any way to subscribe to text changes? 

### ISSUE THREAD

**Issue by microcoder-py** [AppFlowy-IO/appflowy-editor#472]
### Description

Is there any functions kinda like onEditorStateChange(){} we can subscribe to so that I can save any content changes instantaneouly? Or will I need to do something like periodically save it?

### Impact

Easier to save notes without having to get user to explicitly click on save, dispose() method is not always triggered

**Comment by LucasXu0** [comment]
```dart
          editorState.transactionStream.listen((event) {
            if (event.$1 == TransactionTime.after) {
              onEditorStateChange(editorState);
            }
          });
```

Please refer to `transactionStream`. You can listen to it to receive the changes.

**Comment by marcio-ota** [comment]
Error on dispose editorState:
A ValueNotifier<int> was used after being disposed.
