### ISSUE TITLE
[Bug] build error on Flutter 3.13 not released

### ISSUE THREAD

**Issue by Josecodesalot** [AppFlowy-IO/appflowy-editor#494]
### Bug Description

The error where appflowy broke on Flutter 3.13 has been fixed here:

https://github.com/AppFlowy-IO/appflowy-editor/commit/f06abaffa3e74a6389e603631ef160809c738a75

However, it is not deployed to pub.dev yet.

### How to Reproduce

Import the latest appflowly on the latest flutter (3.13.4) 

### Expected Behavior

App does not start

### Operating System

MacOS

### AppFlowy Editor Version(s)

1.40.0

**Comment by LucasXu0** [comment]
Bumped the version 1.4.1.

https://pub.dev/packages/appflowy_editor
