### ISSUE TITLE
[Bug] URLs not being recognised in content inserted via EditorState.insertTextAtPosition()

### ISSUE THREAD

**Issue by microcoder-py** [AppFlowy-IO/appflowy-editor#499]
### Bug Description

I am getting some content from a URL and inserting it into the note editor. However, when I execute the function, the URLs are not being recognized

### How to Reproduce

Using the function

### Expected Behavior

URLs are automatically recognised

### Operating System

Windows 11, when running on web

### AppFlowy Editor Version(s)

1.3.0

**Comment by microcoder-py** [comment]
I have been through the source code for this. A simple fix would be to replace editorState.insertText[AtPosition] functions with the EditorStateCopyPaste extension functions and allowing us to create the nodes manually/automatically detecting the nodes with code the way it is done in copy paste

**Comment by LucasXu0** [comment]
Yes, the URL won't be recognized when using `insertTextAtPosition` because this function only supports inserting **plain text**. If you're trying to parse the URL from the content, you can convert the content to delta format and insert it using `insertTextDelta`.

**Comment by microcoder-py** [comment]
@LucasXu0 what function can I use for delta conversion?
