### ISSUE TITLE
[Bug] bullet and number list issue when select the bullet or number list  text and press enter

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#507]
### Bug Description

when selecting the bullet and list text and then press enter the the next node shifted to paragraph node instead on starting with list next index

### How to Reproduce

**Mobile**
just select the text and press enter on mobile selection does different behaviour and selection handles did not removed to remove handles need to press again or type text

https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/950efdf7-fb2d-4667-ac7d-74e8f39a3ede

**Desktop**
after selection in list and press enter the editor became unresponsive and
start on next line but is did some strange behaviours
 

https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/2ec6a538-3f7f-4404-b8d3-a00581b3f54c

### Expected Behavior

editor need to remember list and start writing on next list index

https://github.com/AppFlowy-IO/appflowy-editor/assets/71745182/244d0670-9aeb-4d76-b989-7de769091b0a

### Operating System

All

### AppFlowy Editor Version(s)

main

**Comment by LucasXu0** [comment]
closed as completed.
