### ISSUE TITLE
Does it not support mobile platforms?

### ISSUE THREAD

**Issue by Dboy233** [AppFlowy-IO/appflowy-editor#51]
On the desktop it works fine, but on mobile it's a bit confusing.😒

**Comment by LucasXu0** [comment]
Hey, @Dboy233. As Pub.dev shows, AppFlowy Editor now officially supports desktop platforms. This quarter, I will work on supporting the mobile platform.

<img width="458" alt="Screenshot 2023-04-10 at 10 40 20" src="https://user-images.githubusercontent.com/11863087/230814683-a7227852-3af3-4183-9f50-342dac44f496.png">
