### ISSUE TITLE
[Bug]Mobile keyboard cursor move not working

### ISSUE THREAD

**Issue by tilemoon** [AppFlowy-IO/appflowy-editor#52]
https://user-images.githubusercontent.com/37775224/230836755-50d6b96a-7903-4f5a-baca-4bd935d836fa.MP4

when I move cursor on software keyboard, cursor in editor not update.

**Comment by LucasXu0** [comment]
Hey, @tilemoon. We haven't fully supported the mobile platform yet. We have plans to do so this quarter.

Related issue: https://github.com/AppFlowy-IO/appflowy-editor/issues/47

**Comment by tilemoon** [comment]
> Hey, @tilemoon. We haven't fully supported the mobile platform yet. We have plans to do so this quarter.
> 
> Related issue: #47

I'm glad to contribute for mobile platform, is there guide or documentation for new contributor ?

**Comment by annieappflowy** [comment]
Home base: https://github.com/AppFlowy-IO/appflowy-editor/issues/68
FYI, @tilemoon , mobile development just started
