### ISSUE TITLE
[Bug] The input mode is not sensitive

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#521]
### Bug Description

[✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64, locale
    zh-Hans)
    • Flutter version 3.13.5 on channel stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 12fccda598 (3 weeks ago), 2023-09-19 13:56:11 -0700
    • Engine revision bd986c5ed2
    • Dart version 3.1.2
    • DevTools version 2.25.0

The input mode is not sensitive, and there will be a state of unresponsive operation when performing line breaks or operations.

### How to Reproduce

When inserting, click Enter or /

### Expected Behavior

Can perform actions quickly

### Operating System

desktop

### AppFlowy Editor Version(s)

master

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/c7c44827-5100-490f-b42c-c1e4e7e2f8c8

**Comment by LucasXu0** [comment]
I can produce it in Flutter 3.13, but not in 3.10. There must be a breaking change in the latest Flutter version.

**Comment by q200892907** [comment]
Hello, when will flutter 3.13 be adapted?

**Comment by LucasXu0** [comment]
I'll be adapting the editor to the latest version next week and will also need to update the minimum supported version.

**Comment by Jei-sKappa** [comment]
@LucasXu0 probably you already knew this but in case I found that the commit from which this problem occurs is "[fix: skip the uncessary text editing value update on macOS](https://github.com/AppFlowy-IO/appflowy-editor/commit/704b65c328480d1d49c86c1f2788ceb282d79e59)".
Android and iOS works for me, it only happens in MacOS (btw I've not tested Windows and Linux).
I'm testing in Flutter (Channel stable, 3.13.1, on macOS 13.5.1 22G90 darwin-arm64)

**Comment by parcool** [comment]
The bug still exists. My current version is Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN). Any updates on this?

**Comment by q200892907** [comment]
Using the latest version, this problem has not yet occurred.
