### ISSUE TITLE
Render serialized output of editor as HTML for browsers.

### ISSUE THREAD

**Issue by e200** [AppFlowy-IO/appflowy-editor#533]
Would be very useful in the future to be able to render the same serialized output this package produces as HTML in browsers.

This would allow people to build rich text tools also outside of Flutter and take this package to another level as Quill already does (with Quill.js and Flutter Quill who share the same delta).

I would like to use this package, but I'm also building my app to support web with HTML and I'm wondering if I save this package serialized content, I will not be able to show it on browsers as HTML... I know this is entirely Flutter, but maybe it is possible?

**Comment by alihassan143** [comment]
@e200  you can use this package converted html in browsers and its output in html inn compatible with most of the editors

**Comment by e200** [comment]
> @e200  you can use this package converted html in browsers and its output in html is compatible with most of the editors

Hi @alihassan143. Do you mean this package already has an HTML exporter? Asking because I didn't see it in the docs. As far as see, docs only mention importing from Markdown or Quill delta.

How do I export the serialized content to HTML?

**Comment by alihassan143** [comment]
yes this package already have import and export html plugin

**Comment by alihassan143** [comment]
you can check example app
[Example App](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/example/lib/home_page.dart)

**Comment by e200** [comment]
The example code has **Unimplemented** HTML and Delta exporters.

**Comment by e200** [comment]
But yes, you're right. I saw the HTML plugin in the lib folder. Thanks for the feedback! This package rocks! 🔥

**Comment by shobith10** [comment]
@e200  please do specify where did you find the HTML plugin ?? is this available inside this package itself ? 
i need to convert data to html , to save in database
