### ISSUE TITLE
[Bug] [web] type Chinese, there is a horizontal line on the text 输入中文 顶部有黑色横线

### ISSUE THREAD

**Issue by ChenHaoTech** [AppFlowy-IO/appflowy-editor#536]
### Bug Description

<img width="744" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/32390273/ff64298e-2781-4b10-b3ab-47d8495b4903">
When I type Chinese, there is a horizontal line on the text

input method is sogou input method

### How to Reproduce

git hash: 7317eb9333fa15ed0c4f1c4d39b0f281aa8c8add

 fl run -d chrome

### Expected Behavior

There is no horizontal line

### Operating System

Apple M2 Pro

### AppFlowy Editor Version(s)

https://github.com/AppFlowy-IO/appflowy-editor/commit/7317eb9333fa15ed0c4f1c4d39b0f281aa8c8add

**Comment by chenhaoaixuexi** [comment]
Running on Mac OS does not have this problem 🙏

**Comment by LucasXu0** [comment]
I can't reproduce it in Flutter 3.10.4. It seems like it's an auto-correct hover line.
