### ISSUE TITLE
[Bug] header/footer is long list, use Column or Row drawing long lists affects performance

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#537]
### Bug Description

header/footer is long list, use Column or Row drawing long lists affects performance

### How to Reproduce

header/footer set up a very long list

### Expected Behavior

Support multiple headers and footers

### Operating System

all

### AppFlowy Editor Version(s)

master

**Comment by q200892907** [comment]
#518

**Comment by Xazin** [comment]
Performance in your application in release mode? Do you have some samples?

**Comment by q200892907** [comment]
@Xazin Add a comment list at the end of the editor and sort the content into a complex structure. If there are too many comments, lazy loading will improve performance.
