### ISSUE TITLE
[Bug] focus issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#542]
### Bug Description

header/footer is TextField，focus issus

### How to Reproduce

First click the editor, then click the header/footer TextField
My environment is flutter 3.13

### Expected Behavior

focus correct

### Operating System

desktop

### AppFlowy Editor Version(s)

master

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/08462521-b177-46e0-ab48-164d00f779e7

### Additional Context

#520 unsolved
flutter 3.13.x

**Comment by LucasXu0** [comment]
I attempted to upgrade the minimum supported version to 3.13; however, I encountered too many unexpected issues. Therefore, I recommend using Flutter 3.10 instead for now.

Similar to this issue, it functions properly in Flutter 3.10.x but not in 3.13.x.

**Comment by q200892907** [comment]
Left and right key operations are blocked in the input boxes at the head and tail of the editor. @LucasXu0
