### ISSUE TITLE
[Bug]  Flutter web Slash command menu Overflows

### ISSUE THREAD

**Issue by dawarepramod4** [AppFlowy-IO/appflowy-editor#545]
### Bug Description

When i use margin to any parent widget in the widget tree the / command menu goes to out of the screen.
you can see in the below image the slash command menu is out of the screen. sometimes it goes all out.
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/91264300/0b76e1d7-efa8-4dea-aeed-05a95ff96dfd)

### How to Reproduce

In the example code 
1. Remove the padding from "example/lib/pages/desktop_editor.dart" 

![Screenshot from 2023-10-20 21-36-11](https://github.com/AppFlowy-IO/appflowy-editor/assets/91264300/2bb816a7-a1ca-4a17-9f7a-d53f92447185)

3. Add below line in the "example/lib/pages/editor.dart" file container.
margin: const EdgeInsets.symmetric(horizontal: 200),
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/91264300/4cc321c7-e8ff-4229-af62-72203635afe7)

### Expected Behavior

The slash Command Menu should not overflow from screen and should be adjusted in the visible area of the widget.

### Operating System

Ubuntu 23.04

### AppFlowy Editor Version(s)

1.4.4 

### Screenshots

-

### Additional Context

-

**Comment by dawarepramod4** [comment]
Or If i give width to the parent container of the editor then also the position mistmatches

**Comment by stevenosse** [comment]
Hi @LucasXu0 
I think this issue can be closed

**Comment by LucasXu0** [comment]
closed as completed.
