### ISSUE TITLE
[Bug] The named parameter 'onLiveTextInput' is required, but there's no corresponding argument. Try adding the required argument.

### ISSUE THREAD

**Issue by dawarepramod4** [AppFlowy-IO/appflowy-editor#546]
### Bug Description

The example Code has followinf problem in "example/lib/pages/mobile_editor.dart"
The named parameter 'onLiveTextInput' is required, but there's no corresponding argument. Try adding the required argument.

### How to Reproduce

Just clone the repo and run Example project. You will see missing_argument_error.

### Expected Behavior

The should not pop up.

### Operating System

Ubuntu 23.04

### AppFlowy Editor Version(s)

1.4.4

### Screenshots

![Screenshot from 2023-10-20 23-03-09](https://github.com/AppFlowy-IO/appflowy-editor/assets/91264300/88d2e401-7fba-41a0-b742-487a79c69dfa)

### Additional Context

-

**Comment by dawarepramod4** [comment]
I have solved the issue.. i think this was solved by @LucasXu0 's commit the changes are not visible in the  main branch.. i have raised PR. Please Check!

**Comment by annieappflowy** [comment]
Hi @dawarepramod4 , we're eager to gather valuable feedback from our users to better plan for 2024. Participants who complete this survey will gain priority access to our new launches. We appreciate your insights: https://tally.so/r/nW8qAQ.
