### ISSUE TITLE
[Bug] mobile_toolbar/_QuitEditingBtn/onTap Not active

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#554]
### Bug Description

mobile_toolbar/_QuitEditingBtn/onTap Not active

### How to Reproduce

tap hide keyboard

### Expected Behavior

active

### Operating System

mobile

### AppFlowy Editor Version(s)

master

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/d3be69d7-fdf8-4efc-9a04-9a0042c2c738)

**Comment by rituraj2000** [comment]
Could you please elaborate the issue more?

**Comment by q200892907** [comment]
Clicking the hidden keyboard in the toolbar on the mobile terminal does not work
