### ISSUE TITLE
[Bug] Mobile Selection doesn't support long press

### ISSUE THREAD

**Issue by robinjhuang** [AppFlowy-IO/appflowy-editor#568]
### Bug Description

I ran the library under examples on an ios Simulator and local ios Device. 

Expected behavior: Long press anywhere on the editor should open a "Select All | Select" pop up. Dragging in the editor should select all the text in the drag action. This is how native ios TextFields work. 

Actual Behavior: You can only select text by double tapping. 

Is this the desired behavior? Do I need to do anything special to achieve the "Expected behavior" above? 

Thanks for the great work! Opening this to clarify something I haven't been able to figure out.

### How to Reproduce

Open iOS simulator. 

```
cd examples/lib
flutter run 
```

Click mouse, holding it and drag across some text. 

### Expected Behavior

Expecting the text to be selected on drag but it's not.

### Operating System

ios

### AppFlowy Editor Version(s)

1.5.0

**Comment by LucasXu0** [comment]
> Long press anywhere on the editor should open a "Select All | Select" pop up. 

@robinjhuang tap at the same position twice will trigger the toolbar.

> Expecting the text to be selected on drag but it's not.

I can't reproduce it. Do you mean that you can't select the text by dragging the handler?

**Comment by robinjhuang** [comment]
Yes! I was expecting to be able to select the text on drag. Is this supposed to be supported? I can change this to a feature request if not.

I thought all text on iOS supports select by dragging.

Robin

**Comment by LucasXu0** [comment]
The editor supports text selection by dragging the handlers. Is this what you want, just like the video shows?


https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/85ca9e22-8065-4717-8cdf-7e7f32dbf457

**Comment by robinjhuang** [comment]
Very close. When you press down without any selected text, I expected the AdaptiveTextSelectionToolbar to appear as well. I thought this was the normal iOS text field behavior.

https://github.com/AppFlowy-IO/appflowy-editor/assets/5674242/47940b33-c25d-4197-846d-f10c7661416a

**Comment by robinjhuang** [comment]
Very close. I wish the AdaptiveTextSelectionToolbar would appear even when you press on a section without selected text. If you want to paste something for example.


https://github.com/AppFlowy-IO/appflowy-editor/assets/5674242/7456b546-6e77-47fa-b234-7692ab840a77

**Comment by alihassan143** [comment]
@LucasXu0  longpress on text and start dragging this is not support by the editor

**Comment by annieappflowy** [comment]
Hi @robinjhuang and @alihassan143 , we're eager to gather valuable feedback from our users to better plan for 2024. Participants who complete this survey will gain priority access to our new launches. We appreciate your insights: https://tally.so/r/nW8qAQ.

**Comment by armandsLa** [comment]
Looks like this issue is related:
https://github.com/AppFlowy-IO/appflowy-editor/issues/667
