### ISSUE TITLE
[Bug] input chinese issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#576]
### Bug Description

Use the Chinese input method to input English first and then input Chinese directly, and the English disappears.

### How to Reproduce

Use the Chinese input method to input English first and then input Chinese directly, and the English disappears.

### Expected Behavior

Displayed correctly

### Operating System

desktop

### AppFlowy Editor Version(s)

master

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/bb1ded64-66bc-4aba-b88b-734f3e6f2213

**Comment by LucasXu0** [comment]
occur in Flutter 3.13.x?

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/e3fd82f4-7ccf-4fbe-b1d4-72aa83f83a50

I'm unable to reproduce it in Flutter master channel.

**Comment by q200892907** [comment]
Yes！flutter 3.13.x

**Comment by q200892907** [comment]
> Untitled.mov 
> I'm unable to reproduce it in Flutter master channel.

Enter text and then enter a space before entering Chinese.

**Comment by q200892907** [comment]
https://github.com/AppFlowy-IO/appfloy-editor/assets/4517301/05141432-fc6c-4325-b2f4-d58aa2caea88
@LucasXu0

**Comment by q200892907** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/316b49bc-1b40-4115-b591-42167450e6e2

@LucasXu0
