### ISSUE TITLE
[Bug] Image upload not working on mobile.

### ISSUE THREAD

**Issue by CodeHariK** [AppFlowy-IO/appflowy-editor#585]
### Bug Description

Problems :
1. Overlay is displayed on top left corner, no alignment option, no customisation option.
2. Url Image upload not working on mobile but working on desktop and web.
3. File Picker gives error when picking image on mobile, not on web or desktop.

### How to Reproduce

```dart
IconButton(
  onPressed: () {
    showImageMenu(
      Overlay.of(context),
      editorState,
      SelectionMenu(
        context: context,
        editorState: editorState,
        selectionMenuItems: [],
      ),
    );
  },
  icon: const Icon(Icons.image),
),
```

Click it on Mobile.

### Expected Behavior

Problems :
1. Overlay is displayed on top left corner, no alignment option, no customisation option.
2. Url Image upload not working on mobile but working on desktop and web.
3. File Picker gives error when picking image on mobile, not on web or desktop.

```dart
flutter: Exception: You are setting a type [FileType.image]. Custom extension filters are only allowed with FileType.custom, please change it or remove filters.
flutter: #0      FilePickerIO._getPath
file_picker_io.dart:78
flutter: #1      FilePickerIO.pickFiles
file_picker_io.dart:36
flutter: #2      FilePicker.pickFiles
file_picker_impl.dart:23
flutter: #3      _UploadImageMenuState._buildFileUploadContainer.<anonymous closure>
image_upload_widget.dart:293
flutter: #4      GestureRecognizer.invokeCallback
recognizer.dart:275
flutter: #5      TapGestureRecognizer.handleTapUp
tap.dart:654
flutter: #6      BaseTapGestureRecognizer._checkUp
tap.dart:311
flutter: #7      BaseTapGestureRecognizer.handlePrimaryPointer
tap.dart:244

```

### Operating System

Apple M2 MacOs Sonoma Version 14.0 (23A344) Darwin Apple.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112 arm64

### AppFlowy Editor Version(s)

appflowy_editor: ^1.5.2

**Comment by LucasXu0** [comment]
Hi, @CodeHariK. I haven't included the image toolbar item on the mobile platform yet. Since the interactions on mobile are diverse, you can easily customize your mobile image block and mobile image toolbar item by extending this editor package. Here's a sample video you can refer to.

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/86564099-39ff-4166-a68a-2c538d958072

**Comment by KevRiver** [comment]
@LucasXu0 Is image toolbar item added to mobile platform now? I'm on latest Flutter SDK version (4.0.0) but I can't find it. I need the feature just like the video you uploaded above. By any chance, is there any plans to provide editor customization examples for Flutter beginners like me? 🥹

**Comment by KevRiver** [comment]
@LucasXu0 I need the same UI just like you've showed in the comment above! I'm using `appflowy_editor@4.0.0` Flutter package for making mobile application. May I ask you to give some sence of image block component customization? It would be very helpful 🥹

**Comment by LucasXu0** [comment]
@KevRiver There’s a widget called MobileToolbarV2, and you can easily customize the toolbar items using it. All you need to do is add the items to the toolbarItems. A kind reminder: if you want to integrate the image menu item, make sure to check the photo library permissions. The code you can refer to is:

https://github.com/AppFlowy-IO/AppFlowy/blob/05c1924940e7dcd232067399ec505655cfc811c0/frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_attachment_item.dart#L4
