### ISSUE TITLE
[Bug] Up and down arrow problem

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#589]
### Bug Description

Appears after setting a relatively large block spacing

flutter 3.13.9
appflowy-editor The latest version

### How to Reproduce

Watch video example

### Expected Behavior

normal movement

### Operating System

desktop

### AppFlowy Editor Version(s)

main

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/35486d8c-f884-4c1e-a42e-ad996b0c88f8)

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/21894a1a-e494-4862-bd95-25beecf5e2f9

**Comment by Xazin** [comment]
I'm not sure what you mean by vertical padding affecting the movement you're doing.

You're moving within the same paragraph, can you elaborate on which part of the video showcases the issue?

**Comment by q200892907** [comment]
I can't move to the next block if I keep pressing the arrow. Likewise, I can't move if I press the up arrow. It has no effect on the same block. @Xazin

**Comment by Xazin** [comment]
On MacOS the up arrow works, but not the down arrow :+1:
