### ISSUE TITLE
[FR] Improvements to the Enter key

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#590]
### Description

If nothing is entered after the tab key, just press Enter to perform the rollback operation.

### Impact

Have a better experience in list-like blocks

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/8623229d-a5ce-4120-b4fd-e42150de2f3e

**Comment by q200892907** [comment]
In the video, the rollback operation is performed by pressing Enter.

**Comment by LucasXu0** [comment]
@q200892907, Can you also make a PR for your numbered list features(for the second-level numbered list, use alpha instead of a number)?

**Comment by q200892907** [comment]
> @q200892907，你也可以为你的编号列表功能做一个 PR（对于二级编号列表，使用 alpha 而不是数字）？

@LucasXu0 Okay, I will submit the changes later

**Comment by q200892907** [comment]
@LucasXu0 PR submitted
