### ISSUE TITLE
[FR] Plaintext support

### ISSUE THREAD

**Issue by Sesa1988** [AppFlowy-IO/appflowy-editor#606]
### Description

Hi,

it would be great to have the option to get a plain text version in order to show some basic preview of some note.
Something like: editorState.document.toPlainText()

### Impact

Its pretty hard to display a preview for multiple notes in a list and I would need to load the editor a lot of times and do also styling with different font sizes for everything.

**Comment by annieappflowy** [comment]
Hi @Sesa1988 , we're eager to gather valuable feedback from our users to better plan for 2024. Participants who complete this survey will gain priority access to our new launches. We appreciate your insights: https://tally.so/r/nW8qAQ.

**Comment by LucasXu0** [comment]
It's pretty easy to do that.

```dart
final nodes = editorState.document.root.children;
final buffer = StringBuffer();
for (final node in nodes) {
  final delta = node.delta;
  if (delta != null) {
    buffer.writeln(delta.toPlainText());
  } else {
    // customize your own text representation for the node
    // for example,
    if (node.type == DividerBlockKeys.type) {
      buffer.writeln('---');
    }
  }
}
final plainTexts = buffer.toString();
```
