### ISSUE TITLE
[Bug] The shortcut keys in the input method are blocked by the editor

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#610]
### Bug Description

The shortcut keys in the input method are blocked by the editor

### How to Reproduce

For example, when using the system Chinese input method, the operation of switching word selection using the up, down, left and right keys is no longer available.

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/93cf634c-0727-4e0d-8842-5028623668b5

### Expected Behavior

When using the input method, do not display its shortcut keys and make the cursor position operable.

https://github.com/AppFlowy-IO/appflowy-editor/assets/4517301/10393bdb-4f7e-42bb-af81-c3dddf73c8ad

### Operating System

desktop

### AppFlowy Editor Version(s)

main

**Comment by q200892907** [comment]
@LucasXu0 @Xazin

**Comment by annieappflowy** [comment]
Hi @q200892907 , thanks for your active participation in our projects!
We're eager to gather valuable feedback from our users to better plan for 2024. Participants who complete this survey will gain priority access to our new launches. We appreciate your insights: https://tally.so/r/nW8qAQ
