### ISSUE TITLE
Couldn't find constructor 'TextScaler.linear'.

### ISSUE THREAD

**Issue by kevan-mtl** [AppFlowy-IO/appflowy-editor#617]
### Bug Description

I get the below error in the Debug Console when trying to launch my app:

```
Error (Xcode): ../../../../../../.pub-cache/hosted/pub.dev/appflowy_editor-2.1.0/lib/src/editor/block_component/bulleted_list_block_component/bulleted_list_block_component.dart:227:29: Error: Couldn't find constructor 'TextScaler.linear'.

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

```

### How to Reproduce

1. Install `appflowy_editor 2.1.0`
2. Add the `AppFlowyEditorLocalizations.delegate`

```
return MaterialApp.router(
                locale: _resolveLocale(state),
                localizationsDelegates: const [
                  ...AppLocalizations.localizationsDelegates,
                  AppFlowyEditorLocalizations.delegate,
                ],
                supportedLocales: AppLocalizations.supportedLocales,
                routerDelegate: getIt<GoRouter>().routerDelegate,
                routeInformationParser:
                    getIt<GoRouter>().routeInformationParser,
                routeInformationProvider:
                    getIt<GoRouter>().routeInformationProvider,
                debugShowCheckedModeBanner: false,
                theme: AppTheme.stdTheme,
                builder: EasyLoading.init(),
              );
```

### Expected Behavior

I expect my app to load as usual - works like a charm normally.

### Operating System

iOS

### AppFlowy Editor Version(s)

2.1.0

**Comment by LucasXu0** [comment]
Hi, @kevan-mtl. Which flutter version do you use?

**Comment by kevan-mtl** [comment]
hi @LucasXu0 

Here is a quick flutter doctor extract

```
[✓] Flutter (Channel stable, 3.13.9, on
    macOS 13.5.1 22G90 darwin-arm64, locale
    en-CA)
    • Flutter version 3.13.9 on channel
      stable at
      /Users/kevansaba/Developer/flutter
    • Upstream repository
      https://github.com/flutter/flutter.gi
      t
    • Framework revision d211f42860 (7
      weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android
    devices (Android SDK version 33.0.0)
    • Android SDK at
      /Users/kevansaba/Library/Android/sdk
    • Platform android-33, build-tools
      33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home
      /bin/java
    • Java version OpenJDK Runtime
      Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    (Xcode 14.3.1)
    • Xcode at
      /Applications/Xcode.app/Contents/Deve
      loper
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at
      /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/
      9212-flutter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/
      6351-dart
    • Java version OpenJDK Runtime
      Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition
    (version 2022.2.3)
    • IntelliJ at /Applications/IntelliJ
      IDEA CE.app
    • Flutter plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/
      9212-flutter
    • Dart plugin can be installed from:
      🔨
      https://plugins.jetbrains.com/plugin/
      6351-dart

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual
      Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) •
      5C4CB06D-71B8-4D65-8AD6-20EC8633A3E7
      • ios            •
      com.apple.CoreSimulator.SimRuntime.iO
      S-17-0 (simulator)
    • macOS (desktop)            • macos
      • darwin-arm64   • macOS 13.5.1 22G90
      darwin-arm64
    • Chrome (web)               • chrome
      • web-javascript • Google Chrome
      119.0.6045.199

[✓] Network resources
    • All expected network resources are
      available.

• No issues found!
```

**Comment by q200892907** [comment]
> hi @LucasXu0
> 
> Here is a quick flutter doctor extract
> 
> ```
> [✓] Flutter (Channel stable, 3.13.9, on
>     macOS 13.5.1 22G90 darwin-arm64, locale
>     en-CA)
>     • Flutter version 3.13.9 on channel
>       stable at
>       /Users/kevansaba/Developer/flutter
>     • Upstream repository
>       https://github.com/flutter/flutter.gi
>       t
>     • Framework revision d211f42860 (7
>       weeks ago), 2023-10-25 13:42:25 -0700
>     • Engine revision 0545f8705d
>     • Dart version 3.1.5
>     • DevTools version 2.25.0
> 
> [✓] Android toolchain - develop for Android
>     devices (Android SDK version 33.0.0)
>     • Android SDK at
>       /Users/kevansaba/Library/Android/sdk
>     • Platform android-33, build-tools
>       33.0.0
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/Contents/Home
>       /bin/java
>     • Java version OpenJDK Runtime
>       Environment (build
>       11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     (Xcode 14.3.1)
>     • Xcode at
>       /Applications/Xcode.app/Contents/Deve
>       loper
>     • Build 14E300c
>     • CocoaPods version 1.12.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google
>       Chrome.app/Contents/MacOS/Google
>       Chrome
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at
>       /Applications/Android
>       Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨
>       https://plugins.jetbrains.com/plugin/
>       9212-flutter
>     • Dart plugin can be installed from:
>       🔨
>       https://plugins.jetbrains.com/plugin/
>       6351-dart
>     • Java version OpenJDK Runtime
>       Environment (build
>       11.0.12+0-b1504.28-7817840)
> 
> [✓] IntelliJ IDEA Community Edition
>     (version 2022.2.3)
>     • IntelliJ at /Applications/IntelliJ
>       IDEA CE.app
>     • Flutter plugin can be installed from:
>       🔨
>       https://plugins.jetbrains.com/plugin/
>       9212-flutter
>     • Dart plugin can be installed from:
>       🔨
>       https://plugins.jetbrains.com/plugin/
>       6351-dart
> 
> [✓] VS Code (version 1.81.0)
>     • VS Code at /Applications/Visual
>       Studio Code.app/Contents
>     • Flutter extension version 3.76.0
> 
> [✓] Connected device (3 available)
>     • iPhone 14 Pro Max (mobile) •
>       5C4CB06D-71B8-4D65-8AD6-20EC8633A3E7
>       • ios            •
>       com.apple.CoreSimulator.SimRuntime.iO
>       S-17-0 (simulator)
>     • macOS (desktop)            • macos
>       • darwin-arm64   • macOS 13.5.1 22G90
>       darwin-arm64
>     • Chrome (web)               • chrome
>       • web-javascript • Google Chrome
>       119.0.6045.199
> 
> [✓] Network resources
>     • All expected network resources are
>       available.
> 
> • No issues found!
> ```

The latest version requires flutter 3.16.x

**Comment by kevan-mtl** [comment]
Perfect, i'll upgrade, thanks!
