### ISSUE TITLE
[Bug] Focusnode not working

### ISSUE THREAD

**Issue by alterhuman** [AppFlowy-IO/appflowy-editor#630]
### Bug Description

I have a title textfield in the editor header and have added the logic to set the focus to the editor when the user submits (presses enter) in the title text field, but the editor is not getting focus.

### How to Reproduce

This is sample code to reproduce this:

Title Textfield:
```dart
class EditorTitleTextField extends StatelessWidget {
  final TextEditingController textController;
  final bool autoFocus;
  final FocusNode nextFocusNode;
  const EditorTitleTextField({
    super.key,
    this.autoFocus = true,
    required this.textController,
    required this.nextFocusNode,
  });

  @override
  Widget build(BuildContext context) {
    
    return TextFormField(
      decoration: InputDecoration(
        hintText: 'Add title',
      ),
      autofocus: autoFocus,
      enabled: true,
      textInputAction: TextInputAction.next,
      onEditingComplete: () {
        FocusScope.of(context).requestFocus(nextFocusNode);
      },
      maxLines: null,
      keyboardType: TextInputType.multiline,
      controller: textController,
    );
  }
}
```

Pass the focusNode of editor to the nextFocusNode.

### Expected Behavior

The editor should get the focus.

### Operating System

macOS Sonoma 17.2

### AppFlowy Editor Version(s)

2.1.0

**Comment by maelchiotti** [comment]
Tried the exact same thing, not working either.

Simple reproducible exemple :

```dart
import 'package:appflowy_editor/appflowy_editor.dart';
import 'package:flutter/material.dart';

class Example extends StatefulWidget {
  const Example();

  @override
  State<Example> createState() => _NotesPageState();
}

class _NotesPageState extends State<Example> {
  final editorState = EditorState.blank();
  final editorFocusNode = FocusNode();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextField(
          textInputAction: TextInputAction.next,
          onSubmitted: (_) {
            editorFocusNode.requestFocus();
          },
        ),
        Expanded(
          child: AppFlowyEditor(
            focusNode: editorFocusNode,
            editorState: editorState,
          ),
        ),
      ],
    );
  }
}
```

**Comment by maelchiotti** [comment]
@alterhuman no, but I didn't try anything else than the code I posted

**Comment by maelchiotti** [comment]
@alterhuman no idea, never tried that sorry

**Comment by LucasXu0** [comment]
> @maelchiotti Got it. A bit off topic question, do you have an idea on how to reduce the default paragraph spacing in appflowyeditor? I'm unable to find an option.

use `BlockComponentConfiguration` to customize the padding.

**Comment by LucasXu0** [comment]
In your case, I think you need to listen to the event of the focus node, and update the selection of the editor when the text field loses focus.

**Comment by saif-ellafi** [comment]
@LucasXu0 @alterhuman 

It is unfortunate that this does not work and was still closed. editorstate.selection is only a workaround for that particular case.
Any ideas on why FocusNodes are not working at all? Can't call certain events when focusing on the AppFlowyTextEditor.

Best regards
