### ISSUE TITLE
[Bug] Unable to set line-height on nodes, causing unwanted visual changes and centering/alignment issues

### ISSUE THREAD

**Issue by hellohabit** [AppFlowy-IO/appflowy-editor#636]
### Bug Description

I have not found a way to provide a static line-height for any nodes in AppFlowyEditor. This causes issues where the line-height will visually change for a single node when including a character with more padding (e.g. emojis). This is more obvious for bulleted/numbered list nodes, where the list-indicator becomes uncentered. This causes undesired visual inconsistency and also makes it difficult to keep the core text center-aligned with list-item indicators (e.g. when building a custom checkbox component where the checkbox is larger in height than the text's line-height).

### How to Reproduce

Paste an emoji into a normal paragraph node or a bulleted/numbered list node in the provided example repo:

https://github.com/AppFlowy-IO/appflowy-editor/assets/127775585/bb4b1c28-811b-4b0e-96cc-f3fddf1abcdb

### Expected Behavior

The AppFlowyEditor library would provide a simple way to set a fixed line-height, to prevent certain text characters from dynamically changing it and support center-alignment with large custom node indicators.

### Operating System

All

### AppFlowy Editor Version(s)

2.1.0

**Comment by hellohabit** [comment]
Also, since this was my first post on this repo, I wanted to thank your team for providing this awesome library! I would love to help maintain and contribute to bug fixes once I launch my app!

**Comment by LucasXu0** [comment]
> Also, since this was my first post on this repo, I wanted to thank your team for providing this awesome library! I would love to help maintain and contribute to bug fixes once I launch my app!

Thank you, you are welcome to contribute to our codebase.

**Comment by LucasXu0** [comment]
It seems this issue is not related to the line height. As this screenshot shows, the emoji and text in the system text field are not centered either.

<img width="212" alt="Screenshot 2024-01-01 at 15 11 15" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/14376d6a-651e-4896-938e-feb38a478063">

**Comment by hellohabit** [comment]
Regardless of the cause of this issue, it still seems like undesired behavior for the text to visibly shift when entering an emoji. That doesn't occur in the build in Flutter TextField components, or most software in general.

Additionally, while potentially unrelated, do you have advice on how to set a static line height and/or align text vertically centered within a node? For example, as displayed in the video above, if I create a custom Todo List Node builder where the checkbox is larger than the text line height, there doesn't seem to be any way to vertically center the text with the check box.

https://github.com/AppFlowy-IO/appflowy-editor/assets/127775585/dadf7296-993f-4e77-bbb2-f3b3fb0b8343

**Comment by LucasXu0** [comment]
In the case of the checkbox, you need to increase the font size because the text extends beyond one line. Despite this, the checkbox will remain centered aligned with the text, which is not the desired behavior.

**Comment by hellohabit** [comment]
I agree that the checkbox should remain at the top when the text expands past one line, but what if I still want to center the checkbox with very first line? I think it's reasonable to support the checkbox being larger than the default line height without having to increase the font size.

**Comment by LucasXu0** [comment]
Yes, I agree. Do you have any good ideas on how to implement it?

**Comment by hellohabit** [comment]
The way I would think we could have the most flexibility would be to completely detach the height of a ListBlock's iconBuilder from the height of the text content itself, so it could be as large as it needs to be. And then also provide some way to provide padding to only the text content, so the developer could center the text content with the iconBuilder content as desired.

**Comment by armandsLa** [comment]
I'm having the same issue. Numbered list and Bullet list alignment is off when adding emoji. Even without emoji, they are off by few pixels. Can't find a way to reliably center them.

![Simulator Screenshot - iPhone 15 Pro - 2024-01-10 at 14 57 11](https://github.com/AppFlowy-IO/appflowy-editor/assets/6855713/00635541-9d6b-4ffc-8138-5440df6155e6)

![Simulator Screenshot - iPhone 15 Pro - 2024-01-10 at 14 57 18](https://github.com/AppFlowy-IO/appflowy-editor/assets/6855713/8c5373ea-c2b9-4bf9-b71e-5db3c2623f57)

**Comment by LucasXu0** [comment]
Setting the line height in text style configuration will solve this issue.

```dart
    return EditorStyle.desktop(
      cursorWidth: 2.0,
      cursorColor: Colors.blue,
      selectionColor: Colors.grey.shade300,
      textStyleConfiguration: TextStyleConfiguration(
        text: GoogleFonts.poppins(
          fontSize: 16,
          color: Colors.black,
          height: 1.5,
        ),
        code: GoogleFonts.architectsDaughter(),
        bold: GoogleFonts.poppins(
          fontWeight: FontWeight.w500,
        ),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 40),
      maxWidth: 640,
    );
```

<img width="120" alt="Screenshot 2024-12-12 at 11 17 03" src="https://github.com/user-attachments/assets/8b4a4910-97fb-4243-9254-a61ad0210b1b" />
