### ISSUE TITLE
[FR] Support edit for Code (for attributes: {code: true})

### ISSUE THREAD

**Issue by Mikhail-Ivanou** [AppFlowy-IO/appflowy-editor#637]
### Description

Why code block cannot be in   supportSliced ?
Now I get normal text when insert chars in code block.

 static List<String> supportSliced = [
    bold,
    italic,
    underline,
    strikethrough,
    textColor,
    highlightColor,
  ];

  // The values supported toggled even if the selection is collapsed.
  static List<String> supportToggled = [
    bold,
    italic,
    underline,
    strikethrough,
    code,
  ];

### Impact

Correct UX when edit code block
Actual
attributes: {delta: [{insert: Style, attributes: {code: true}}, {insert: Q}, {insert: dtext, attributes: {code: true}}]},
Expected
attributes: {delta: [{insert: StyleQdtext, attributes: {code: true}}]},

Once I input Q in the text

**Comment by LucasXu0** [comment]
```dart
  AppFlowyRichTextKeys.supportSliced.add(AppFlowyRichTextKeys.code);
```

Hi, @Mikhail-Ivanou. You can customize the supported format as shown in the code above.
