### ISSUE TITLE
[FR] Support text align

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#64]
### Description

for the example user want to align text at center 
there no attribute for aligning text node 

### Impact

With this most of the Rich Text editor features will be completed

**Comment by ArslanYM** [comment]
Can I work on this issue?

**Comment by LucasXu0** [comment]
<img width="1229" alt="Screenshot 2023-08-29 at 16 23 38" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/ca30fc59-fb73-44e7-b5b0-42123ff5d7df">

This feature has been supported in the main branch.
