### ISSUE TITLE
[Bug] MobileToolbarTheme seems not customizable

### ISSUE THREAD

**Issue by MichalNemec** [AppFlowy-IO/appflowy-editor#640]
### Bug Description

I am trying to modify color of icons in mobile toolbar, but i cant, because i cannot change values in MobileToolbarTheme.

### How to Reproduce

MobileToolbarTheme select dark mode and you will see that some icons are black.

### Expected Behavior

Colorization of MobileToolbarTheme enabled for devs.

### Operating System

macOS

### AppFlowy Editor Version(s)

2.1.0

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/5663019/c583abe4-d277-4d60-98d8-08edebdd0d0f)

### Additional Context

The white icons are copied and forced custom color, the close button as you can see is not forced, its permanently black.

**Comment by LucasXu0** [comment]
Hi, @MichalNemec. Please use MobileToolbarV2 instead.  

```
final Color iconColor;
```
