### ISSUE TITLE
[Bug] autoFocus does not work when the editor is empty

### ISSUE THREAD

**Issue by stevenosse** [AppFlowy-IO/appflowy-editor#645]
### Bug Description

When the editor is initialised with a blank document, the autoFocus attribute does not seem to work.

### How to Reproduce

Create a blank document:

```dart
final document = Document.blank();
final editorState = EditorState(document: document);
```
Initialise the editor:

```dart
AppFlowyEditor(
      editorState: _editorState,
      editorScrollController: _editorScrollController,
      showMagnifier: true,
      autoFocus: true,
)
```

### Expected Behavior

The keyboard should open

### Operating System

Android 14

### AppFlowy Editor Version(s)

2.1.0

**Comment by LucasXu0** [comment]
I can't reproduce it on the main branch.

**Comment by stevenosse** [comment]
Found a workaround, closing this.
