### ISSUE TITLE
[FR] Support local image picker

### ISSUE THREAD

**Issue by rileyhawk1417** [AppFlowy-IO/appflowy-editor#65]
### Description

Pick images from local computer, and use them in AppFlowy-Editor.

### Impact

Users are able to add images from their device

**Comment by LucasXu0** [comment]
closed as completed. 

<img width="619" alt="Screenshot 2023-07-12 at 17 03 16" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/474a1ef1-a146-4c70-87fa-e7d6b5d40897">
