### ISSUE TITLE
[FR] iOS support cursor positioning with longpress spacebar

### ISSUE THREAD

**Issue by mikivanou** [AppFlowy-IO/appflowy-editor#651]
### Description

It's possible to drag cursor in common text input after longpress spacebar.
It will be great to have similar feature for Appflowy editor in iOS

Steps: I tap spacebar and wait it become grey (all keyboard), then move my finger to left or right. Cursor in textfield follows this movement.

### Impact

common UX for iOS

### Additional Context

https://github.com/AppFlowy-IO/appflowy-editor/assets/142427747/31e2ff04-4815-4ae4-9891-d8fd99bbd689

**Comment by LucasXu0** [comment]
Good insight

**Comment by mikivanou** [comment]
Great job! 
Thanks a lot :)

**Comment by armandsLa** [comment]
Unfortunately, the issue still persists. I have just tested it with version 2.3.0. Not only does the drag cursor not work, but after performing that action, deletion often stops working. Please refer to the attached video for demonstration.

Uploading appflowy_drag_cursor.mov…

**Comment by LucasXu0** [comment]
@armandsLa I only tested it with the system built-in keyboard. Can you use the system one and try again?

**Comment by armandsLa** [comment]
On iOS simulator with system keyboard it works on the second try. First try also doesn't move the cursor.

SwiftKey keyboard is the most popular keyboard on iOS, installed on more than 30% of iOS devices. It's worth testing on it as well.
