### ISSUE TITLE
[FR] Expose cursorWidth

### ISSUE THREAD

**Issue by alterhuman** [AppFlowy-IO/appflowy-editor#653]
### Description

Ability to change the cursor width similar to the cursor color.

### Impact

This is available in flutter textfields and for people who use this, having a different cursor width in just one place is inconsistent. Exposing `cursorWidth` as a parameter similar to `cursorColor` would be great.

**Comment by LucasXu0** [comment]
@alterhuman FYI, https://github.com/AppFlowy-IO/appflowy-editor/pull/654
