### ISSUE TITLE
Text style(bold, italic etc.) are lost when enabled on empty line and the starting editing

### ISSUE THREAD

**Issue by armandsLa** [AppFlowy-IO/appflowy-editor#664]
### Bug Description

Text style(bold, italic etc.) are lost when selecting on empty line and then starting the edit by tapping in text field to open they keyboard. They work fine when closing menu by "X" and then starting to type.

### How to Reproduce

1. Open empty editor
2. Open text decoration menu and select "Bold"
3. Tap somewhere in the text field to begin editing
4. Type something

### Expected Behavior

Text style to persist no matter how text editing is started

### Operating System

Flutter/iOS

### AppFlowy Editor Version(s)

2.2.0

**Comment by LucasXu0** [comment]
Actually, it's intentionally designed that way. The active text formatting style will be cleared when you select a new line or change the cursor position.
