### ISSUE TITLE
Keyboard drag to position cursor is not working

### ISSUE THREAD

**Issue by armandsLa** [AppFlowy-IO/appflowy-editor#667]
### Bug Description

Most keyboards(like SwiftKey on iOS) has an ability to hold down space bar to drag the cursor to the desired location. When trying to perform this action in editor, the cursor is not being moved. This works with Flutter text fields.

### How to Reproduce

Open editor and enter some text. Then try to move cursor by holding down the space bar using SwiftKeys on iOS

### Expected Behavior

Cursor to be dragged

### Operating System

Flutter/iOS

### AppFlowy Editor Version(s)

2.2.0

**Comment by LucasXu0** [comment]
close as duplicated https://github.com/AppFlowy-IO/appflowy-editor/issues/651

FYI, I will bump a new version later today
