### ISSUE TITLE
[Bug] Issue with new lines and capitalization

### ISSUE THREAD

**Issue by armandsLa** [AppFlowy-IO/appflowy-editor#669]
### Bug Description

It appears that when adding a new line, the editor also inserts an invisible character that causes the keyboard to lose capitalization. Deletion is also affected, requiring two backspace actions to move back to the previous line.

Please see the attached video demonstrating how the keyboard switches between capitalization states. This issue is only visible with SwiftKeys, not with the iOS default keyboard.

https://github.com/AppFlowy-IO/appflowy-editor/assets/6855713/76a021b2-e860-46a8-bc64-75160b968533

### How to Reproduce

1. Open editor on iOS that uses SwiftKeys keyboard
2. Add few new lines
3. Try deleting those new lines

### Expected Behavior

To work as expected

### Operating System

Flutter/iOS

### AppFlowy Editor Version(s)

2.2.0

**Comment by armandsLa** [comment]
Just tested with `2.3.0` version and the deletion issue is gone. Capitalization still persists.

**Comment by LucasXu0** [comment]
Yes. I added a transparent symbol at the beginning of the line. You can see the reason here.

https://github.com/AppFlowy-IO/appflowy-editor/blob/f053a1ee798460cc824970731fc318970e2e7777/lib/src/editor/editor_component/service/ime/non_delta_input_service.dart#L202

**Comment by armandsLa** [comment]
At this point, all I can add is that I also tested this on `flutter_quill`, and there were no issues with new lines. Maybe it's worth looking into how they have solved this issue.

P.S. SwiftKey keyboard is the most popular keyboard on iOS, installed on more than 30% of iOS devices. It's worth testing on it as well.

**Comment by LucasXu0** [comment]
@armandsLa Sure, I conducted a brief test using `flutter_quill` and found the same fundamental issue. You can reproduce it by following these steps:

1. Mark the text as a bulleted list.
2. Move the cursor to the beginning of the line and click the 'X' button.
3. You will notice that the formatting is not removed.

<img width="198" alt="Screenshot 2024-01-15 at 15 03 58" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/ffafdfbd-ff3a-482c-8466-a73bb9bacf7a">

**Comment by LucasXu0** [comment]
That's the reason why I inserted a transparent symbol at the beginning of the text to enable the deletion of the format from anywhere. Also, I'm trying to find a better way to solve it.
