### ISSUE TITLE
[Bug] The currsor can't catch up with my new input words when I write fastly

### ISSUE THREAD

**Issue by forrestsocool** [AppFlowy-IO/appflowy-editor#67]
### Bug Description

https://user-images.githubusercontent.com/3960433/231692099-d7fd1985-e54b-403d-8df9-b377c0beaf90.mp4

### How to Reproduce

type fast in an empty document

### Expected Behavior

currsor always at last

### Operating System

Windows

### AppFlowy Editor Version(s)

0.1.6

**Comment by LucasXu0** [comment]
Thanks for reporting.

**Comment by LucasXu0** [comment]
Fixed in latest version.

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/bfbaab72-08e5-458d-8335-a9649cd5cec1
