### ISSUE TITLE
[Bug] serializeToMarkdown doesn't support nested lists

### ISSUE THREAD

**Issue by alterhuman** [AppFlowy-IO/appflowy-editor#671]
### Bug Description

Using `serializeToMarkdown` to save editor content shows nested lists on top level itself when deserialized back to document format. It's working correctly when using json.

### How to Reproduce

- Add data with nested numbered list
- Use `serializeToMarkdown` to store editor data 
- Then load it back into the editor

### Expected Behavior

The nesting should retain.

### Operating System

MacOS

### AppFlowy Editor Version(s)

2.3.0

**Comment by LucasXu0** [comment]
closed as completed.
