### ISSUE TITLE
Build Failing Due To NodeVistor Issue

### ISSUE THREAD

**Issue by RonitBanerjee** [AppFlowy-IO/appflowy-editor#678]
### Bug Description

I am getting this error message which is not allowing me to build the application.  I tried various versions of the pluging starting from 1.4.0 to 2.3.0 but nothing works issue was observed between 9:45 PM to 10:30 PM Indian Time.
The class 'NodeVisitor' can't be used as a mixin because it isn't a mixin class nor a mixin.
    with md.NodeVisitor {

### How to Reproduce

flutter build web

### Expected Behavior

build should ideally complete without any issues, but it is failing with the above mentioned error message, I tried various versions of the pluging starting from 1.4.0 to 2.3.0 but nothing works issue was observed between 9:45 PM to 10:30 PM Indian Time.

### Operating System

Windows 11

### AppFlowy Editor Version(s)

2.3.0, 1.5.2, 1.4.0, and more

**Comment by Xazin** [comment]
Hi Ronit,

There seems to be something clashing in your project, can you provide a minimum reproducible code that we can use to test?

**Comment by rnp0728** [comment]
I have cloned the repo and there seems to an error in markdown_decoder.dart
 
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/98372124/baa7be9a-c09f-49dd-9fd4-5473c52e7284)

changed it to 
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/98372124/1e0d8be1-ad4a-47ce-bf42-cc8de9ce49fe)

This fixed the issue for us. Can you check on your end?

**Comment by RonitBanerjee** [comment]
@Xazin Can you please look into this, it has stopped the builds for the app.

**Comment by Xazin** [comment]
> @Xazin Can you please look into this, it has stopped the builds for the app.

I don't see this issue in the Editor, and it runs fine on web for me.

I'm on Flutter version `3.18.0-0.2.pre`, and the file in question hasn't been changed for 5 months.

What is your Flutter version?

**Comment by martijn96** [comment]
> I have cloned the repo and there seems to an error in delta_markdown_decoder.dart
> 
> ![image](https://private-user-images.githubusercontent.com/98372124/297843895-baa7be9a-c09f-49dd-9fd4-5473c52e7284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjE4NDksIm5iZiI6MTcwNTc2MTU0OSwicGF0aCI6Ii85ODM3MjEyNC8yOTc4NDM4OTUtYmFhN2JlOWEtYzA5Zi00OWRkLTlmZDQtNTQ3M2M1MmU3Mjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE0MzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MDlmYzAyOGRlMTJhYjMwOGNkYjY4MjdlNWM2MjQ3MmQ0YjUyMTJmMTkwZjA4ZmU0YmQ1MGY1Njk2NGFlN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aaQDvsdVnjHd7XFU41Us6weTX1S79nVgkmgrPQjrpns)
> 
> changed it to ![image](https://private-user-images.githubusercontent.com/98372124/297844059-1e0d8be1-ad4a-47ce-bf42-cc8de9ce49fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjE4NDksIm5iZiI6MTcwNTc2MTU0OSwicGF0aCI6Ii85ODM3MjEyNC8yOTc4NDQwNTktMWUwZDhiZTEtYWQ0YS00N2NlLWJmNDItY2M4ZGU5Y2U0OWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE0MzkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4YTU5MWM0MzVlNjFkZGI1ZjRhZjg0MjkxMTQ1OTM3Nzg3NmYyNjM1MTU3MWI2MmYzZjM1OGVmZTdmYzIyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8oTXGUsIoZAR6UnKgP-yGSzNVOQf7KR19eZhfly-q0w)
> 
> This fixed the issue for us. Can you check on your end?

For me this also worked, thanks!

@Xazin I'm running:
Flutter 3.16.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 67457e669f (4 days ago) • 2024-01-16 16:22:29 -0800
Engine • revision 6e2ea58a5c
Tools • Dart 3.2.5 • DevTools 2.28.5

**Comment by rnp0728** [comment]
@Xazin I am on Flutter 3.16.8 channel stable

**Comment by RonitBanerjee** [comment]
I am on Flutter 3.16.2

**Comment by penkzhou** [comment]
maybe you guys should check the version of `markdown` which is introduced by this editor. now the buggy version is `7.2.1` or `7.2.0`. 
I fallback the `markdown`version  into `7.1.1` and it works for me.
check this out.[https://github.com/dart-lang/markdown/commits/master/](url)

**Comment by konstantin-mohin** [comment]
the same on macOS 
```
delta_markdown_decoder.dart:10:10: Error: The class 'NodeVisitor' can't be used as a mixin because it isn't a mixin class nor a mixin.
    with md.NodeVisitor {
         ^
```

**Comment by RonitBanerjee** [comment]
@Xazin Rudra's solution is a valid one, Can you make the change and update it?
