### ISSUE TITLE
[FR] Mobile Support

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#68]
### Description

We will soon begin work related to supporting Mobile, therefore I have started mapping out some of the subtasks that relate. For some of the subtasks, it will be valid to open a separate issue due to the amount of work or complexity of the task.

The list of subtasks is subject to change, as work starts we will discover more items.

**Must haves:**
- [x] [BUG] Modify example application to fit on mobile
- [x] [BUG] Refactor InputService, KeyboardService, and Shortcuts, to accommodate mobile
- [x] [BUG] Popovers/Overlays such as the SelectionMenu is overflowing on mobile
- [ ] #307
- [x] [BUG] It is not possible to close the Soft Keyboard
- [x] [BUG] It is not possible to scroll in the editor on mobile
- [ ] [BUG] ScrollPosition should follow the cursor on mobile
- [ ] [BUG] Cannot delete a newline at the beginning of a delta (eg. TextDelta does not move up to the previous line, and cannot delete list/checkbox item)
- [x] [FR] Soft Keyboard should show a newline button instead of submit/done
- [x] [BUG] Add support for Query Schemes for Android and iOS in the example app, see: https://pub.dev/packages/url_launcher#configuration - Consider adding a section to the readme about this
- [x] #308

We should create separate issues for tasks that contain more complexity or is open to discussion.

### Impact

We will be able to support mobile not only with the editor itself but it is also required for https://github.com/AppFlowy-IO/appflowy to support mobile.

### Additional Context

This feature is part of the roadmap, we can create a milestone to track it, or add a new label eg. `mobile-support` or just `mobile` to make work related to this feature visible.

**Comment by LucasXu0** [comment]
Thank you for your summary. Great job!

>  [BUG] Refactor InputService, KeyboardService, and Shortcuts, to accommodate mobile

FYI, I'm working on the second part.

**Comment by rileyhawk1417** [comment]
Should we give the user an option for fullscreen mode?  Currently by default the editor hides the system notification bar.

**Comment by allytiago** [comment]
It will also be very nice if there is optimized support for Samsung DeX. Desktop interface for Samsung devices
https://developer.samsung.com/samsung-dex

**Comment by allytiago** [comment]
https://developer.samsung.com/samsung-dex

**Comment by matthewwong525** [comment]
It seems like there's support mobile platform as of `1.0.0-dev0` . Could we get an update on this ticket? Is this ticket completed and are all the must haves covered?

**Comment by LucasXu0** [comment]
@Xazin How about breaking down this issue to some tickets?

**Comment by hyj1204** [comment]
@Xazin 
I plan to refactor the `MobileSelectionGestureDetector` and fix #308

**Comment by Xazin** [comment]
> @Xazin 
> 
> I plan to refactor the `MobileSelectionGestureDetector` and fix #308 together

Perfect 😍

**Comment by AkechiShiro** [comment]
Hi @Xazin besides the two bugs left is there anything major missing before this issue can be closed, I guess this is initial support towards the mobile app

**Comment by Xazin** [comment]
For now we will close this, most issues have already been completed thanks to Lucas and Yijing.
