### ISSUE TITLE
[Bug] blocked on latest stable 'NodeVisitor'

### ISSUE THREAD

**Issue by lukepighetti** [AppFlowy-IO/appflowy-editor#694]
### Bug Description

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/appflowy_editor-2.3.0/lib/src/plugins/markdown/decoder/delta_markdown_decoder.dart:10:10: Error: The class 'NodeVisitor' can't be used as a mixin because it isn't a mixin class nor a mixin.

### How to Reproduce

  appflowy_editor: ^2.3.0
Flutter 3.16.9 • channel stable

### Expected Behavior

launches

### Operating System

macOS

### AppFlowy Editor Version(s)

above

**Comment by stevenosse** [comment]
Hi @lukepighetti 
As a work_around to this, i've forced to use of markdown > 7.1 in my pubspec.yaml :

```yaml
dependency_overrides: 
  markdown: ^7.1.0
```
