### ISSUE TITLE
[Bug] Version 2.3.1 is breaking on the web.

### ISSUE THREAD

**Issue by adsonpleal** [AppFlowy-IO/appflowy-editor#702]
### Bug Description

As I mentioned on this PR https://github.com/AppFlowy-IO/appflowy-editor/pull/701 some `Platform.is<PLATFORM>` calls are breaking the web build of `2.3.1` version.

### How to Reproduce

Just start a new project and add `appflowy_editor: ^2.3.1` as a dependency. Run it targeting the web and start typing in the editor. An exception will be thrown. 

If you use the master branch version you'll see a different error, only when selecting a text and replacing it.

### Expected Behavior

It should not throw exceptions when editing the text on the web.

### Operating System

Web

### AppFlowy Editor Version(s)

2.3.1

## 2.3.1 version
<img width="998" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11666470/abcec949-8d0c-4952-9232-fe7e51be9ff5">

## master branch
<img width="982" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11666470/bdb509e8-d353-4dac-9098-5465b29942d3">

### Additional Context

While investigating the code I found out that calls to `Platform.is<PLATFORM>` are breaking on the web.

[One example is this call.](https://github.com/AppFlowy-IO/appflowy-editor/blob/3832f4e752c186e284ce423ca3f6ad82d2bb6a83/lib/src/editor/editor_component/service/ime/delta_input_on_replace_impl.dart#L32).

My guess is that [PlatformExtension](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/lib/src/editor/util/platform_extension.dart) should be used instead of calling `Platform.is<PLATFORM>` directly.

Searching the codebase I noticed that a recent PR added some direct calls. If we search for [Platform.is](https://github.com/search?q=repo%3AAppFlowy-IO%2Fappflowy-editor%20Platform.is&type=code) we find some direct calls outside the PlatformExtension file. I guess that there should be no direct calls outside `PlatformExtension`.

**Comment by LucasXu0** [comment]
thanks for reporting. bumped a new version 2.3.2.
