### ISSUE TITLE
[FR] Trigger mobile toolbar menu item from shortcut

### ISSUE THREAD

**Issue by MichalNemec** [AppFlowy-IO/appflowy-editor#704]
### Description

Hello, is there a way when i have shortcut "$" to trigger on mobile, random text menu in toolbar, to start to write within toolbar?
 

### Impact

uniform communication on desktop and mobile with triggering functionalities, which enables faster typing.

### Additional Context

We have $ shortcut on desktop which then opens up a floating menu (like links) where you can pick random text (fed from ai), then its written into content.
We would like similar thing for mobile. when $ is written, it opens up in mobile toolbar that specific menu to pick and choose.

**Comment by LucasXu0** [comment]
@MichalNemec in your case, I suggest customizing your own toolbar or you're welcome to submit your implementation. for now, our built-in toolbar only appears when the editor is focused.
