### ISSUE TITLE
[Bug] Slash Command Menu Items

### ISSUE THREAD

**Issue by moesaid** [AppFlowy-IO/appflowy-editor#708]
### Bug Description

Awesome work, guys! I'm really enthusiastic about the project! Today, I began my exploration today, but I couldn't find information on how or where we can interact with 'Slash Command Menu Items.'

Is there an accessible API for this widget?

### How to Reproduce

Slash Command

### Expected Behavior

ability to customize the menu and its items 

### Operating System

mac

### AppFlowy Editor Version(s)

2.3.2

### Screenshots

<img width="546" alt="Screenshot 2024-02-07 at 7 53 09 PM" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/38924585/36b3bbb2-d8b5-4e9e-beaa-cb2137eb0053">

**Comment by moesaid** [comment]
@LucasXu0  I wanna pick your brain on that one, what's your thoughts?

**Comment by at15** [comment]
It is in the shortcut commands

https://github.com/AppFlowy-IO/appflowy-editor/blob/796d1249fe5a7f936cb9060208561c45db484098/lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart#L5-L35

**Comment by LucasXu0** [comment]
There's a configuration named `customSlashCommand`. You can customize your menu items using this configuration.

**Comment by andynvt** [comment]
> customSlashCommand

how to use this on the editor?

**Comment by 0xharkirat** [comment]
like this:
```dart
    return AppFlowyEditor(
      editorState: editorState,
      autoFocus: true,
      characterShortcutEvents: [
        customSlashCommand( // <- like this
          [...standardSelectionMenuItems, codeBlockMenuItem],
        ),
        ...standardCharacterShortcutEvents,
        ...codeBlockCharacterEvents,

        backticksToCodeBlock,
      ],
      commandShortcutEvents: [
        ...standardCommandShortcutEvents,
      ],

      editorStyle: EditorStyle.desktop(),
      blockComponentBuilders: customBuilder(),
    );
  }
```

this is my `codeBlockMenuItem`:
```dart


final SelectionMenuItem codeBlockMenuItem = SelectionMenuItem(
  getName: () => 'Code Block',
  icon: (editorState, isSelected, style) => SelectionMenuIconWidget(
    icon: Icons.code,
    isSelected: isSelected,
    style: style,
  ),
  keywords: ['code', 'code block', 'snippet', '```'],
  handler: (editorState, _, __) async {
    final selection = editorState.selection;
    if (selection == null || !selection.isCollapsed) return;

    final currentNode = editorState.getNodeAtPath(selection.end.path);
    if (currentNode == null) return;

    final parent = currentNode.parent;
    final parentPath = parent?.path;
    final index = parent?.children.indexOf(currentNode);
    if (parentPath == null || index == null || index == -1) return;

    final codeBlock = codeBlockNode(delta: Delta()..insert(''));
    final insertPath = parentPath.child(index + 1);

    final transaction = editorState.transaction
      ..insertNode(insertPath, codeBlock)
      ..afterSelection = Selection.collapsed(
        Position(path: insertPath, offset: 0),
      );

    await editorState.apply(transaction);
  },
);
```

Note: when passing to characterShortcutEvents: 

the order matters, because the customSlashCommand should override the slashCommand with the default menu in ...standartCharacterEvents
