### ISSUE TITLE
[FR] Ability to have a Read-Only View / Disable Editing

### ISSUE THREAD

**Issue by zambetpentru** [AppFlowy-IO/appflowy-editor#716]
### Description

Is there a recommended way to disable editing / text selection / toolbars so that I can have a read only view to show my users?

### Impact

To be able to create content that can then be rendered and shown to my users.

**Comment by Xazin** [comment]
You can set `editable` to `false`, in EditorState.

Let me know if what you meant was something else.

**Comment by zambetpentru** [comment]
Brilliant, I was just about to update that I found it!
