### ISSUE TITLE
[Bug] Table Icon visible on hover in ReadOnly and causes exception when clicked

### ISSUE THREAD

**Issue by zambetpentru** [AppFlowy-IO/appflowy-editor#717]
### Bug Description

When running the Example app and setting Editable = false the table icons are visible and cause an exception when clicked.

### How to Reproduce

1. Start the demo App in Editable:false

2. Click on the Icon on the table:

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/81489824/2bab5550-8cf3-4081-9958-a858fcc19186)

3. Error
![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/81489824/c2c538c3-9bde-4841-9a8e-83be0062ffd7)

### Expected Behavior

Icon should not be visible in ReadOnly?

### Operating System

MacOS

### AppFlowy Editor Version(s)

2.3.2

**Comment by Taverz** [comment]
@LucasXu0  Please, сlose this issue
