### ISSUE TITLE
[FR] Recommended way to extract text from document, e.g. for Search

### ISSUE THREAD

**Issue by zambetpentru** [AppFlowy-IO/appflowy-editor#718]
### Description

Hi, is there a recommended way to extract all the unformatted text from a AppFlowy document?

### Impact

I intend to integrate this text information into the rest of content search in Postgres

**Comment by LucasXu0** [comment]
@zambetpentru Do you want only the raw texts, or do you prefer the raw JSON with text format?

If you only need the raw texts, you can iterate through the `document`.

```dart
final document = editorState.document;
final startNode = document.first;
if (startNode == null) {
  // return or throw an error
} else {
  final iterator =
      NodeIterator(document: document, startNode: startNode);
  final texts = <String>[];

  while (iterator.moveNext()) {
    final node = iterator.current;
    final delta = node.delta;
    if (delta != null) {
      texts.add(delta.toPlainText());
    }
  }
  debugPrint(texts.toString());
}
```

**Comment by zambetpentru** [comment]
That's great thanks @LucasXu0!
