### ISSUE TITLE
[Bug] Unclear license wording ?

### ISSUE THREAD

**Issue by jacquetc** [AppFlowy-IO/appflowy-editor#731]
### Bug Description

Hello, 

Nice work on this editor !

I was reading the AppFlowy-editor license and [this article](https://fossa.com/blog/dual-licensing-models-explained/) and I was trying to determine if your are in a "Choice-of-license" scenario or a "Multi-license" scenario. To me, it remains unclear if you mean "AGPL *or* MPL" or "AGPL *and* MPL" .

This intellectual "bug" can be on my side since my mother tongue is french, not english. If it's unclear for me, it may also be for others ? 

I can *choose* to understand your license as "AGPL *or* MPL", choose the MLP license, and integrate it in a closed-source software.

Can you please clarify ?

### How to Reproduce

Read the license, line 1, and the end of your Readme
Your wording is "is dual-licensed, and released under both of the following licenses:"

### Expected Behavior

- "AGPL *or* MPL":
"is dual-licensed, and released under both of the following licenses, applying one license or the other:"
- "AGPL *and* MPL"
"is dual-licensed, and released under both of the following licenses, both applying simultaneously:"

### Operating System

License

### AppFlowy Editor Version(s)

d4d35c0d103a5d1bddf68181fcfaf9f75b0fccb5

**Comment by annieappflowy** [comment]
@jacquetc , please check out [this FAQ](https://docs.appflowy.io/docs/documentation/appflowy-editor/licenses) about the license
