### ISSUE TITLE
[FR] Choosing which Block componets are available for text field

### ISSUE THREAD

**Issue by Pebkac03** [AppFlowy-IO/appflowy-editor#738]
### Description

Being able to choose which Block Components you are able to enter in a text field would make the package more usable for applications that are not AppFlowy by enabling the developer to pick and choose which components a user can choose to add between the default ones as well as custom ones the developer might have added.

### Impact

Mainly users of other applications than AppFlowy which uses the package.

**Comment by Xazin** [comment]
I'm not sure what you mean, there is a default set of blocks that are used if the developer doesn't override it.

See https://pub.dev/documentation/appflowy_editor/latest/appflowy_editor/AppFlowyEditor/blockComponentBuilders.html

**Comment by Pebkac03** [comment]
Yes, I see there is the possibility to extend and override but can you also remove the default components: eg.
`
AppFlowyEditor(
  blockComponentBuilders: {
    'my_block_component': MyBlockComponentBuilder(),
    'my_second_block_component': MySecondBlockComponentBuilder(),
  },
);
`

**Comment by Xazin** [comment]
> Yes, I see there is the possibility to extend and override but can you also remove the default components: eg. `AppFlowyEditor( blockComponentBuilders: { 'my_block_component': MyBlockComponentBuilder(), 'my_second_block_component': MySecondBlockComponentBuilder(), }, );`

If you provide a custom value to `blockComponentBuilders`, then none of the standard blocks are included.

The standard blocks are just a fallback Map of blocs in case no value is provided to `blockComponentBuilders`.

**Comment by Pebkac03** [comment]
Then I must have had another factor at play when testing it in my app, it didn't want to work when providing my own map of BlockComponentBuilders. Thanks for the quick reply and sorry for requesting a feature that already existed.

**Comment by Xazin** [comment]
No worries, if you still have questions or are experiencing issues, feel free to join our discord and ask there :+1:

Discord invite: https://discord.gg/xeFSm7n7qZ
