### ISSUE TITLE
[FR] Change license of example to MIT

### ISSUE THREAD

**Issue by lorenz-bienek** [AppFlowy-IO/appflowy-editor#744]
### Description

At the moment the example has the same license as the library. I have the impression that this might not have been the intension as it severely limits the usefulness of the example. This is why I propose on changing the license of the example to one with a maximum of permissiveness like the MIT license.

### Impact

Anybody who uses the example as a starting point as suggested can do so without being forced to open source their app.
Even more importantly using parts of the example code to get started without having to open source those files would be very valuable.

**Comment by annieappflowy** [comment]
@lorenz-bienek , MPL is quite loose in terms of what to open source. Here is a [FAQ](https://docs.appflowy.io/docs/documentation/appflowy-editor/licenses) about the license you may find helpful
