### ISSUE TITLE
[FR] Old version of intl ^0.18.0

### ISSUE THREAD

**Issue by rostislav-maslov** [AppFlowy-IO/appflowy-editor#749]
### Description

Hi!

I found an error when try add **appflowy_editor**. appflowy_editor use old version of **intl**. Can you please update version of intl lib. 

https://pub.dev/packages/intl/versions

**Error description:**
_Because appflowy_editor >=1.0.0-dev.0 depends on **intl ^0.18.0** and pluto_grid 8.0.0 depends on intl ^0.19.0, appflowy_editor >=1.0.0-dev.0 is incompatible with pluto_grid 8.0.0.
And because no versions of pluto_grid match >8.0.0 <9.0.0, appflowy_editor >=1.0.0-dev.0 is incompatible with pluto_grid ^8.0.0.
So, because campus_core_app depends on both pluto_grid ^8.0.0 and appflowy_editor ^2.3.3, version solving failed._

### Impact

All users who use newest version of intl lib.

**Comment by Alvish0407** [comment]
You can try
```yaml
dependency_overrides:
  intl: ^0.19.0
```

**Comment by LucasXu0** [comment]
@penkzhou Thanks for the reminder.

**Comment by LucasXu0** [comment]
https://github.com/AppFlowy-IO/appflowy-editor/pull/797
