### ISSUE TITLE
[Bug] Image node render image first time on coming back to editor again start showing error again

### ISSUE THREAD

**Issue by alihassan143** [AppFlowy-IO/appflowy-editor#76]
### Bug Description

when image added it shows only one time 
when came back from other screen to editor again 

### How to Reproduce

```
  editorState.insertImageNode(
                    "https://images.unsplash.com/photo-1471897488648-5eae4ac6686b?ixlib=rb-1.2.1&dl=sarah-dorweiler-QeVmJxZOv3k-unsplash.jpg&w=640&q=80&fm=jpg&crop=entropy&cs=tinysrgb");
```
    
when render that same document with image loaded again editor start showing error

### Expected Behavior

Editor need to render image again without error

### Operating System

iphone 14 pro simulator  

### AppFlowy Editor Version(s)

0.1.7

### Screenshots

https://user-images.githubusercontent.com/71745182/231955771-0e4d3eac-4553-4a4f-9b7d-622ff609c19b.mov

<img width="1680" alt="Screenshot 2023-04-14 at 11 10 14 AM" src="https://user-images.githubusercontent.com/71745182/231956036-bd63173f-928a-4c3e-ba1b-266b59824e66.png">

**Comment by Xazin** [comment]
@LucasXu0 I can no longer reproduce on Android or iOS.

I believe we can close this.

**Comment by Aruljebaraj** [comment]
any idea how to insert local images
