### ISSUE TITLE
[Bug] TextStyle not preserved on type

### ISSUE THREAD

**Issue by Jei-sKappa** [AppFlowy-IO/appflowy-editor#768]
### Bug Description

When typing in some text span the new characters do not keep the text style from the previous character.

### How to Reproduce

Highlight a text span with link or a code and start typing in the middle.

### Expected Behavior

The newly added characters should have the same text style as the previous character.

### Operating System

MacOS

### AppFlowy Editor Version(s)

2.3.3 (ref: 61d892a09c17182eebeddee9b605624bfca6fc3b)

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/46776108/fa5b79c1-a8df-4ce2-870c-8bd38c4674d3

### Additional Context

This don't happen if writing in bold, italic, ecc..

**Comment by LucasXu0** [comment]
By default, we only preserve the formats contained in the list below. You can enable additional formats to be preserved by adding them to `AppFlowyRichTextKeys.supportSliced.`

```dart
  static List<String> supportSliced = [
    bold,
    italic,
    underline,
    strikethrough,
    textColor,
    backgroundColor,
  ];
```
