### ISSUE TITLE
[FR]  Ability to edit placeholder text

### ISSUE THREAD

**Issue by chimon2000** [AppFlowy-IO/appflowy-editor#800]
### Description

I would like the ability to edit the placeholder text that appears when adding a new paragraph or when creating a blank editor.

### Impact

I am not using the editor in the context of a "notion" clone so I would like to be able to "label" the field, and hide the helper text that pops up for each paragraph.

**Comment by stevenosse** [comment]
Hi @chimon2000 

You can customize the default paragraph placeholder by doing:

```dart
 map[ParagraphBlockKeys.type] = ParagraphBlockComponentBuilder(
     configuration: BlockComponentConfiguration(
         placeholderText: (node) => 'Custom placeholder',
     ),
);
```

Or you mean customizing placeholder for each `paragraphNode` ?

**Comment by LucasXu0** [comment]
For all the placeholders in the text based blocks(paragraph, list, quote ...), you can use BlockComponentConfiguration to customize the placeholder.
