### ISSUE TITLE
Unexpected Double New Line Issue When Pressing Enter.

### ISSUE THREAD

**Issue by Zuhaib50** [AppFlowy-IO/appflowy-editor#812]
### Bug Description

Hello all, I'm running the example code and facing an issue. When I tap 'Enter' to go to the next line, it adds two new lines instead of one. However, when I reach a new line while typing, it behaves correctly and moves to the next line as expected. Can you please check this issue?

### How to Reproduce

Running the example code

### Expected Behavior

Going to new line while typing...

<img width="776" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/59314201/728540ad-3d60-44b5-83e4-21cacce81852">

Going to new line while tap on enter!

<img width="710" alt="image" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/59314201/24996a09-263d-4ce3-9e2a-e8b7024ccaa8">

### Operating System

All

### AppFlowy Editor Version(s)

Latest

**Comment by LucasXu0** [comment]
@Zuhaib50 What do you mean by 'it adds two new lines instead of one'? I think you might need to use `Shift+Enter` to start a new line without padding.

**Comment by zabi50** [comment]
@LucasXu0  how to remove default padding? because on Mobile we cannot press **Shift+Ente**r

**Comment by LucasXu0** [comment]
@zabi50 Please refer to the example code. To remove all the default padding, follow the instructions in the screenshot.

<img width="1017" alt="Screenshot 2024-06-04 at 17 05 47" src="https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/061d54e8-30bf-4519-8311-ad8821765f4a">
