### ISSUE TITLE
[FR] Allow selection of text when the editor is in read only

### ISSUE THREAD

**Issue by Moumen-io** [AppFlowy-IO/appflowy-editor#814]
### Description

I would like to allow my users to select the text when the editor is in read mode. I am using the editor to provide documentations for the users.

### Impact

Users will be able to select and copy data, such as a link or code snippet

**Comment by LucasXu0** [comment]
@Moumen-io This feature is supported in the latest version. When you set editable to false, the selection still works unless you disable it manually.
