### ISSUE TITLE
editor toolbar display is incomplete

### ISSUE THREAD

**Issue by OHeroJ** [AppFlowy-IO/appflowy-editor#815]
### Bug Description

if add the code:
```
SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge)
```

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/12316547/5c871f5c-d943-4e0b-9de3-2659a9583002)

### How to Reproduce

i have no idea

### Expected Behavior

show normal

### Operating System

Android 14

### AppFlowy Editor Version(s)

latest

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/12316547/a38dd8a1-9f92-4b85-bf2d-0f8aa34cce0f)

**Comment by LucasXu0** [comment]
It's a known issue. We need some time to address the keyboard height issue.

**Comment by LucasXu0** [comment]
@OHeroJ Please update the latest main version and set the `maintainBottomViewPadding` to true.

```dart
      body: SafeArea(
        maintainBottomViewPadding: true,
        child: _widgetBuilder(context),
      ),
```
