### ISSUE TITLE
The render result from Markdown with checkbox can not be checked like Appflowy does

### ISSUE THREAD

**Issue by lucasjinreal** [AppFlowy-IO/appflowy-editor#816]
Is this normal?

Also, my data are stores in sql with markdown format, how can I update the markdown itself when checkbox checked?> Thansk!

**Comment by LucasXu0** [comment]
You should listen for changes in the document's transactions and update your markdown accordingly.

**Comment by lucasjinreal** [comment]
Hi, any reference code to listen it's changes?
