### ISSUE TITLE
[Bug] Mobile caret bug with Flutter 3.22

### ISSUE THREAD

**Issue by badayumut** [AppFlowy-IO/appflowy-editor#819]
### Bug Description

Caret has been working incorrectly since flutter 3.22 update. There is a bug in its size and location. can be easily tested in the sample project.

### How to Reproduce

Open the latest version appflowy-editor example project in Flutter 3.22 and above SDK with Android Emulator.
Caret size and location behaves unexpectedly

### Expected Behavior

Caret size and location calculated correctly

### Operating System

Android API 31 - 34

### AppFlowy Editor Version(s)

2.5.0 or latest build on Github

### Screenshots

https://github.com/AppFlowy-IO/appflowy-editor/assets/143794438/ee9cdb07-d305-4a0d-99b9-d7cf9b5f2df0

**Comment by LucasXu0** [comment]
There's a breaking change in Flutter 3.22.x

The `getFullHeightForCaret` didn't respect the font size anymore if it's in the sub level

```dart
                RichText(
                  key: richTextKey,
                  text: const TextSpan(
                    children: [
                      TextSpan(
                        text: 'AppFlowy ',
                        style: TextStyle(
                          inherit: true,
                          color: Color(0xff000000),
                          fontSize: 16.0,
                          decoration: TextDecoration.none,
                        ),
                      ),
                      TextSpan(
                        text: ' Editor',
                        style: TextStyle(
                          inherit: true,
                          color: Color(0xff000000),
                          fontSize: 20.0,
                          decoration: TextDecoration.none,
                        ),
                      ),
                    ],
                  ),
```

# Flutter 3.19.0

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/8892bcba-fa02-4c38-8546-e2442ac0dea7


# Flutter 3.22.0

https://github.com/AppFlowy-IO/appflowy-editor/assets/11863087/86871f04-1baf-4dcb-a7a2-e226d3561574
