### ISSUE TITLE
[Question] How to set the maximum number of rows or height displayed by AppFlowyEditor, especially when displaying multiple AppFlowyEditors in a listview, and preferably with Ellipsis of

### ISSUE THREAD

**Issue by peter100u** [AppFlowy-IO/appflowy-editor#820]
### Description

How to set the maximum number of rows or height displayed by AppFlowyEditor, especially when displaying multiple AppFlowyEditors in a listview, and preferably with Ellipsis of

### Impact

Scene display of note lists, rather than just editing notes

**Comment by realth000** [comment]
Same question, how to set `maxlines` like what we can do in `TextField`.

I use AppFlowy editor in a chat UI, now i'm using `BoxConstraints` to limit max height but it's better if set with line numbers.

Tried `Shrikwrap` but did not work.

**Comment by resfandiari** [comment]
same question

**Comment by resfandiari** [comment]
I founded solution only wrap it with `IntrinsicHeight` widget.

**Comment by LucasXu0** [comment]
There's no way to set the maximum number of lines for appflowy_editor right node. But for the height, you can use `IntrinsicHeight` to wrap the editor.
