### ISSUE TITLE
[Bug] Standard command shortcuts have 2 Delete commands

### ISSUE THREAD

**Issue by Xazin** [AppFlowy-IO/appflowy-editor#823]
### Bug Description

There are 2 Delete command shortcut events, there should only be one, they should be consolidated.

See `deleteCommand` and `backspaceCommand`.

### How to Reproduce

.

### Expected Behavior

.

### Operating System

All

### AppFlowy Editor Version(s)

main

### Screenshots

![image](https://github.com/AppFlowy-IO/appflowy-editor/assets/42929161/ae10dfa5-2279-4189-ae73-eae7c1687b50)

### Additional Context

Their behavior should be the same, the only difference is the command itself, we allow for multiple commands to trigger one event, no need to have two of the same commands, it's redundant.

**Comment by MayurSMahajan** [comment]
Actually, both have different functionality:
`backspaceCommand` deletes the left character from the cursor in Windows
`deleteCommand` deletes the right character from the cursor in Windows.

In Mac, the `deleteCommand` behaves like the backspace in Windows by deleting the left character to the cursor.

**Comment by Xazin** [comment]
> Actually, both have different functionality: `backspaceCommand` deletes the left character from the cursor in Windows `deleteCommand` deletes the right character from the cursor in Windows.
> 
> In Mac, the `deleteCommand` behaves like the backspace in Windows by deleting the left character to the cursor.
