### ISSUE TITLE
[FR]  allow set placeholder text

### ISSUE THREAD

**Issue by swaitw** [AppFlowy-IO/appflowy-editor#85]
### Description

when I use appflowy-editor, i want show some help message as placeholder, for example we can show "press '/' for command" .

### Impact

via setting meaning full placeholder text can make the editor more user friendly and easy to pick it up.

### Additional Context

go a little bit further, may should design some feature to make build in components configurable.

**Comment by LucasXu0** [comment]
```
  ParagraphBlockKeys.type: TextBlockComponentBuilder(
    configuration: standardBlockComponentConfiguration.copyWith(
      placeholderText: (_) => 'Enter a / to insert a block, or start typing',
    ),
  ),
```

It has been supported in the latest version 1.2.4
