### ISSUE TITLE
[Bug] An error occurs when entering Korean on the web platform

### ISSUE THREAD

**Issue by kkundi** [AppFlowy-IO/appflowy-editor#873]
### Bug Description

It seems to be caused by the similar problem as https://github.com/AppFlowy-IO/appflowy-editor/issues/89

### Error message
```
DartError: Unsupported operation: Platform._operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3                              throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                                          _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                                                 get operatingSystem
dart-sdk/lib/io/platform.dart 83:44                                                                      get operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1071:8                         get
dart-sdk/lib/io/platform.dart 161:46                                                                     get isIOS
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1071:8                         get
packages/appflowy_editor/src/editor/editor_component/service/ime/delta_input_on_replace_impl.dart 32:18  onReplace
```

### How to Reproduce

If you input in English in appflowy, there is no problem, but if you input in Korean,  error occurs.

### Expected Behavior

No error

### Operating System

Web (Chrome)

### AppFlowy Editor Version(s)

3.1.0

**Comment by bybabek** [comment]
Same problem. I solved the problem temporarily by:

`  
import 'package:flutter/foundation.dart' show kIsWeb;
if (!kIsWeb) {
      if (Platform.isMacOS && (composingTextRange?.isCollapsed ?? false)) {
        composingTextRange = TextRange.empty;
      }
    } else {
      if (composingTextRange?.isCollapsed ?? false) {
        composingTextRange = TextRange.empty;
      }
    }`

**Comment by adnan-nazir** [comment]
Facing kind of similar exceptoin on Web live, not able to type anything.

```
Uncaught Error: Unsupported operation: Platform._operatingSystem
    at Object.h (main.dart.js:3792:19)
    at Object.dDH (main.dart.js:7992:15)
    at Object.dDJ (main.dart.js:8028:16)
    at main.dart.js:261996:23
    at a.<computed> [as cTN] (main.dart.js:24:36)
    at main.dart.js:261997:24
    at a.<computed> [as dia] (main.dart.js:24:36)
    at main.dart.js:84172:34
    at cM8.a (main.dart.js:5195:63)
    at cM8.$2 (main.dart.js:75071:14)
```

**Comment by adnan-nazir** [comment]
Weird, Started facing on local also 

`DartError: Unsupported operation: Platform._operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3                           throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                                       _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                                              get operatingSystem
dart-sdk/lib/io/platform.dart 83:44                                                                   get operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1091:8                      get
dart-sdk/lib/io/platform.dart 146:48                                                                  get isMacOS
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1091:8                      get
`

**Comment by adnan-nazir** [comment]
Hi @kkundi, are you facing this only on entering special character?

I am not able to type any character.

**Comment by adnan-nazir** [comment]
@LucasXu0 can you please help us to fix this issue?

**Comment by kkundi** [comment]
> Hi @kkundi, are you facing this only on entering special character?
> 
> I am not able to type any character.

I didn't encounter any problems when entering numbers or English.
The problem appears to occur when typing in Korean or Japanese.

Is delta_input_on_replace_impl.dart the part where the problem occurs?
In my problem the code where the problem occurs is [this part](https://github.com/AppFlowy-IO/appflowy-editor/blob/2110fde62ca61746b7dfcf572dc8d78c114494f6/lib/src/editor/editor_component/service/ime/delta_input_on_replace_impl.dart#L32).
I think it will be solved if you just add `PlatformExtension.isMobile`  before that code.

```
if (PlatformExtension.isMobile && Platform.isIOS)
```
However, there is no way to check if this is the right solution, so I am hoping that someone who knows this well will solve it.

**Comment by kkundi** [comment]
@adnan-nazir 

The same problem occurred when using version 3.2.0.
Problems occur even when entering numbers or English in a web.

The isMacOS verification code included in #871 appears to be the cause of the problem.
This is similar to the cause of the problem I first reported.

After modifying to use PlatformExtension locally, the problem disappeared.
I will PR the code that I modified and tested locally.

**Comment by adnan-nazir** [comment]
@kkundi 
I just tested it stated working again but for the slash menu its still throwing exception.


```
DartError: Unsupported operation: Platform._environment
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3                                 throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 279:5                                             _environment
dart-sdk/lib/io/platform_impl.dart 83:17                                                                    get environment
dart-sdk/lib/io/platform.dart 177:59                                                                        get environment
packages/appflowy_editor/src/editor/editor_component/service/shortcuts/character/slash_command.dart 102:30  _showSlashMenu
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                          <fn>
dart-sdk/lib/async/zone.dart 1661:54                                                                        runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                                                  handleValue
dart-sdk/lib/async/future_impl.dart 861:44                                                                  handleValueCallback
dart-sdk/lib/async/future_impl.dart 890:13                                                                  _propagateToListeners
dart-sdk/lib/async/future_impl.dart 666:5                                                                   [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 736:7                                                                   callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                                            _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                                             _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7                                          <fn>
```

**Comment by kkundi** [comment]
@adnan-nazir 

This error occurs because [dart-io is not supported in Flutter web](https://api.flutter.dev/flutter/dart-io/dart-io-library.html).
It means `Platform.environment` cannot be used in Flutter web.

@LucasXu0 

[This code](https://github.com/AppFlowy-IO/appflowy-editor/blob/96ac065b638beee768ba0a8429c89644f42cafa4/lib/src/editor/editor_component/service/shortcuts/character/slash_command.dart#L102) causes an error in flutter web.
I wanted to modify it myself, but I couldn't because I didn't know the exact purpose of adding this code.
Could you please modify this part of code?

If you need to report any other issues, please let me know.

**Comment by LucasXu0** [comment]
@kkundi I'll do that. Thanks for reporting.

**Comment by LucasXu0** [comment]
@kkundi Please try the latest commit on the main branch. I have resolved the issue.

**Comment by kkundi** [comment]
@LucasXu0 

It works! Thanks for the quick fix.
