### ISSUE TITLE
[Bug] MobileFloatingToolbar issue

### ISSUE THREAD

**Issue by q200892907** [AppFlowy-IO/appflowy-editor#890]
### Bug Description

The selected content cannot be displayed when the first action is empty

### How to Reproduce

The first action is empty, the other lines have content, select all can be repeated

### Expected Behavior

Normal display toolbar

### Operating System

mobile

### AppFlowy Editor Version(s)

main

### Screenshots

https://github.com/user-attachments/assets/40708530-4906-4a6d-b3c3-013b031b0bab

### Additional Context

@LucasXu0

**Comment by himmatsingh019** [comment]
Hi, I am facing this issue where the RTF view only shows when keyboard is open. Is there any way to make it static or override by setting some param to true. 

Thanks.
