### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zj1016** [AppFlowy-IO/appflowy-editor#899]
Do all projects that use this pub need to expose the source code

Because I think it's MPL-2.0, AGPL-3.0 license

**Comment by Xazin** [comment]
We changed from AGP-3 to dual licensing with MPL2.

As long as you adhere to the MPL2 part of the license, you're good.

This means that as long as you don't modify the files of the source (appflowy-editor) in your project, you don't need to open-source anything. If you do modify the source files (of appflowy-editor), you would have to fork the project and modify your files there to be compliant (public fork).

It's good to also open a PR with your modifications from your fork, even if they aren't accepted, it might be useful to others.

**Comment by zj1016** [comment]
So I just need to follow MPL2, right? But I see on https://pub.dev/packages/appflowy_editor  that the license is still MPL-2.0, AGPL-3.0 (license).
