### ISSUE TITLE
[Bug] Markdown parser doesn't recognize softline breaks

### ISSUE THREAD

**Issue by TatsuUkraine** [AppFlowy-IO/appflowy-editor#912]
### Bug Description

Markdown parser doesn't recognize softline breaks.
According to markdown specs format like ` \n` (with trailing space) should be treated as softline break. But current parser ignores this part of the markdown making just one unified string

### How to Reproduce

```
markdownToDocument('first line \nsecond line')
```

### Expected Behavior

Output
```
first line
second line
```

### Operating System

Any

### AppFlowy Editor Version(s)

3.3.0

**Comment by TatsuUkraine** [comment]
@LucasXu0 the problem is that \n (with leading space) should be treated as soft line break, and not as paragraph. Additionally, if document contains softline break, it will be converted to a markdown with the wrong format, meaning - document to markdown function will generate just \n without leading space, which is wrong format

**Comment by TatsuUkraine** [comment]
I will try to provide a screenshot of how editor currently renders this format, since markdownToDocument if it receives softline breaks (` \n` pay attention to a leading space), goes through markdown package first, which generates "br" elements, and editor decoder doesn't know what to do with it. At least it was like that in v3

**Comment by TatsuUkraine** [comment]
Yes, markdown package from dart team will generate 3 inline elements from a string like `some \nother`. And the output will be text element "some", inline element with tag "br", text element "other"

**Comment by TatsuUkraine** [comment]
https://www.markdownguide.org/basic-syntax/#line-breaks

**Comment by LucasXu0** [comment]
<img width="1303" alt="Screenshot 2024-10-15 at 21 05 58" src="https://github.com/user-attachments/assets/a5cdfedc-9ea1-4a59-9729-5c8dc4d0db50">

Did you try decoding it using the markdown package? I've added the` md.SoftLineBreakSyntax()`, but it seems to only return 1 paragraph.

**Comment by LucasXu0** [comment]
I misunderstood what you meant. I thought you said 'first line \nsecond line' should generate two paragraphs. Actually, what you need is a paragraph with a line break between these two lines.

**Comment by TatsuUkraine** [comment]
yep yep, exactly 

as for attempts to fix it
here is my solution for now for the decoder

https://github.com/TatsuUkraine/appflowy-editor/blob/markdown-encode/lib/src/plugins/markdown/decoder/delta_markdown_decoder.dart#L57

and for encoder
https://github.com/TatsuUkraine/appflowy-editor/blob/markdown-encode/lib/src/plugins/markdown/encoder/delta_markdown_encoder.dart#L27

Decoder fix is based on flutter_markdown package
https://github.com/flutter/packages/blob/main/packages/flutter_markdown/lib/src/builder.dart#L509

But encoder fix - I'm still not sure that it's the right solution

**Comment by TatsuUkraine** [comment]
@LucasXu0 try 2 spaces before \n

**Comment by TatsuUkraine** [comment]
I probably mislead you with "one space" requirement, sorry. Softline breaks in MD represented as 2 trailing spaces a new  line `  \n`

**Comment by TatsuUkraine** [comment]
as for 1 space and new line, I think editor also did not correctly parse it (probably)

input: `first line \nsecond line`

here is output of flutter_markdown
![Снимок экрана 2024-10-15 в 16 31 32](https://github.com/user-attachments/assets/d37a5b2d-a73e-4f4c-bff0-a2e4ccc6529d)

and here is editor
![Снимок экрана 2024-10-15 в 16 31 38](https://github.com/user-attachments/assets/ca593659-a693-42c5-82ff-2f3636e3fad8)

**Comment by LucasXu0** [comment]
For the '\n' with two spaces, I have submitted a PR. Regarding '\n' with one space, I'm not sure if it should keep the text on the same line. At least from the text content provided by the markdown package, the result contains a '\n'.

https://github.com/AppFlowy-IO/appflowy-editor/pull/933

**Comment by TatsuUkraine** [comment]
@LucasXu0 thanks

One thing I think currently encoder also not correctly transforms document to markdown. For instance if you use shift+enter, in the output markdown it will be just `\n` instead of `  \n`. But I'm not 100% sure. I was trying to fix it like this
https://github.com/TatsuUkraine/appflowy-editor/blob/markdown-encode/lib/src/plugins/markdown/encoder/delta_markdown_encoder.dart#L27

But underlying issue there that it doesn't properly handles all case with softline breaks

**Comment by TatsuUkraine** [comment]
For instance if you have text with underline, you put softline break somewhere in the middle, it produces markdown that can't be recognized by flutter_markdown. And if you try to convert this markdown back to document, editor also won't recognize it properly. I'm unsure if it's related to `UnderlineSyntax` or not. But editor will render input like `<u>some underline  \nwith second line</u>` as
```
<u>some underline
with second line</u>
```
without applying underline styling

**Comment by TatsuUkraine** [comment]
@LucasXu0 could you please reopen this issue? it seems editor still doesn't properly recognize softline breaks
