### ISSUE TITLE
[Bug] deps conflicting with most up to date version of device_info_plus

### ISSUE THREAD

**Issue by TatsuUkraine** [AppFlowy-IO/appflowy-editor#926]
### Bug Description

most up to date version of device_info_plus is 11, but package requires v10

### How to Reproduce

try to install editor into the project with device_info_plus v11

### Expected Behavior

Editor should allow to have device_info_plus v11

### Operating System

any

### AppFlowy Editor Version(s)

4.0.0

**Comment by LucasXu0** [comment]
@TatsuUkraine You can use the latest [commit](https://github.com/AppFlowy-IO/appflowy-editor/commit/b60626f034a9b14e53ea5bce8d249b002371404e) which has upgraded the device_info_plus to v11.0.0

**Comment by TatsuUkraine** [comment]
Thank you
